package com.chenyou.mapper;

import com.chenyou.pojo.ActivityNum;
import com.chenyou.pojo.ActivityNumExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActivityNumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_num
     *
     * @mbggenerated Wed Oct 10 16:35:45 CST 2018
     */
    int countByExample(ActivityNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_num
     *
     * @mbggenerated Wed Oct 10 16:35:45 CST 2018
     */
    int deleteByExample(ActivityNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_num
     *
     * @mbggenerated Wed Oct 10 16:35:45 CST 2018
     */
    int deleteByPrimaryKey(Integer activityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_num
     *
     * @mbggenerated Wed Oct 10 16:35:45 CST 2018
     */
    int insert(ActivityNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_num
     *
     * @mbggenerated Wed Oct 10 16:35:45 CST 2018
     */
    int insertSelective(ActivityNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_num
     *
     * @mbggenerated Wed Oct 10 16:35:45 CST 2018
     */
    List<ActivityNum> selectByExample(ActivityNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_num
     *
     * @mbggenerated Wed Oct 10 16:35:45 CST 2018
     */
    ActivityNum selectByPrimaryKey(Integer activityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_num
     *
     * @mbggenerated Wed Oct 10 16:35:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") ActivityNum record, @Param("example") ActivityNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_num
     *
     * @mbggenerated Wed Oct 10 16:35:45 CST 2018
     */
    int updateByExample(@Param("record") ActivityNum record, @Param("example") ActivityNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_num
     *
     * @mbggenerated Wed Oct 10 16:35:45 CST 2018
     */
    int updateByPrimaryKeySelective(ActivityNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_num
     *
     * @mbggenerated Wed Oct 10 16:35:45 CST 2018
     */
    int updateByPrimaryKey(ActivityNum record);
}