package com.chenyou.mapper;

import com.chenyou.DataSource;
import com.chenyou.pojo.ActivityRank;
import com.chenyou.pojo.ActivityRankExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
@DataSource("dataSource1")
public interface ActivityRankMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_rank
     *
     * @mbggenerated Wed Oct 10 16:44:40 CST 2018
     */
    int countByExample(ActivityRankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_rank
     *
     * @mbggenerated Wed Oct 10 16:44:40 CST 2018
     */
    int deleteByExample(ActivityRankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_rank
     *
     * @mbggenerated Wed Oct 10 16:44:40 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_rank
     *
     * @mbggenerated Wed Oct 10 16:44:40 CST 2018
     */
    int insert(ActivityRank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_rank
     *
     * @mbggenerated Wed Oct 10 16:44:40 CST 2018
     */
    int insertSelective(ActivityRank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_rank
     *
     * @mbggenerated Wed Oct 10 16:44:40 CST 2018
     */
    List<ActivityRank> selectByExample(ActivityRankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_rank
     *
     * @mbggenerated Wed Oct 10 16:44:40 CST 2018
     */
    ActivityRank selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_rank
     *
     * @mbggenerated Wed Oct 10 16:44:40 CST 2018
     */
    int updateByExampleSelective(@Param("record") ActivityRank record, @Param("example") ActivityRankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_rank
     *
     * @mbggenerated Wed Oct 10 16:44:40 CST 2018
     */
    int updateByExample(@Param("record") ActivityRank record, @Param("example") ActivityRankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_rank
     *
     * @mbggenerated Wed Oct 10 16:44:40 CST 2018
     */
    int updateByPrimaryKeySelective(ActivityRank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_rank
     *
     * @mbggenerated Wed Oct 10 16:44:40 CST 2018
     */
    int updateByPrimaryKey(ActivityRank record);
}