package com.chenyou.mapper;

import com.chenyou.DataSource;
import com.chenyou.pojo.AnnualSchedule;
import com.chenyou.pojo.AnnualScheduleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
@DataSource("dataSource1")
public interface AnnualScheduleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_annual_schedule
     *
     * @mbggenerated Wed Dec 26 20:47:16 CST 2018
     */
    int countByExample(AnnualScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_annual_schedule
     *
     * @mbggenerated Wed Dec 26 20:47:16 CST 2018
     */
    int deleteByExample(AnnualScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_annual_schedule
     *
     * @mbggenerated Wed Dec 26 20:47:16 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_annual_schedule
     *
     * @mbggenerated Wed Dec 26 20:47:16 CST 2018
     */
    int insert(AnnualSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_annual_schedule
     *
     * @mbggenerated Wed Dec 26 20:47:16 CST 2018
     */
    int insertSelective(AnnualSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_annual_schedule
     *
     * @mbggenerated Wed Dec 26 20:47:16 CST 2018
     */
    List<AnnualSchedule> selectByExample(AnnualScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_annual_schedule
     *
     * @mbggenerated Wed Dec 26 20:47:16 CST 2018
     */
    AnnualSchedule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_annual_schedule
     *
     * @mbggenerated Wed Dec 26 20:47:16 CST 2018
     */
    int updateByExampleSelective(@Param("record") AnnualSchedule record, @Param("example") AnnualScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_annual_schedule
     *
     * @mbggenerated Wed Dec 26 20:47:16 CST 2018
     */
    int updateByExample(@Param("record") AnnualSchedule record, @Param("example") AnnualScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_annual_schedule
     *
     * @mbggenerated Wed Dec 26 20:47:16 CST 2018
     */
    int updateByPrimaryKeySelective(AnnualSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_annual_schedule
     *
     * @mbggenerated Wed Dec 26 20:47:16 CST 2018
     */
    int updateByPrimaryKey(AnnualSchedule record);
}