package com.chenyou.mapper;

import com.chenyou.DataSource;
import com.chenyou.pojo.AnnualPlanOpen;
import com.chenyou.pojo.AnnualPlanOpenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
@DataSource("dataSource1")
public interface AnnualPlanOpenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_annualplan_open
     *
     * @mbggenerated Wed Dec 26 22:25:39 CST 2018
     */
    int countByExample(AnnualPlanOpenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_annualplan_open
     *
     * @mbggenerated Wed Dec 26 22:25:39 CST 2018
     */
    int deleteByExample(AnnualPlanOpenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_annualplan_open
     *
     * @mbggenerated Wed Dec 26 22:25:39 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_annualplan_open
     *
     * @mbggenerated Wed Dec 26 22:25:39 CST 2018
     */
    int insert(AnnualPlanOpen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_annualplan_open
     *
     * @mbggenerated Wed Dec 26 22:25:39 CST 2018
     */
    int insertSelective(AnnualPlanOpen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_annualplan_open
     *
     * @mbggenerated Wed Dec 26 22:25:39 CST 2018
     */
    List<AnnualPlanOpen> selectByExample(AnnualPlanOpenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_annualplan_open
     *
     * @mbggenerated Wed Dec 26 22:25:39 CST 2018
     */
    AnnualPlanOpen selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_annualplan_open
     *
     * @mbggenerated Wed Dec 26 22:25:39 CST 2018
     */
    int updateByExampleSelective(@Param("record") AnnualPlanOpen record, @Param("example") AnnualPlanOpenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_annualplan_open
     *
     * @mbggenerated Wed Dec 26 22:25:39 CST 2018
     */
    int updateByExample(@Param("record") AnnualPlanOpen record, @Param("example") AnnualPlanOpenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_annualplan_open
     *
     * @mbggenerated Wed Dec 26 22:25:39 CST 2018
     */
    int updateByPrimaryKeySelective(AnnualPlanOpen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_annualplan_open
     *
     * @mbggenerated Wed Dec 26 22:25:39 CST 2018
     */
    int updateByPrimaryKey(AnnualPlanOpen record);


    List<AnnualPlanOpen>listAnnualPlanOpen();
}