package com.chenyou.mapper;

import com.chenyou.pojo.GangGrade;
import com.chenyou.pojo.GangGradeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GangGradeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gang_grade
     *
     * @mbggenerated Fri Sep 14 16:12:33 CST 2018
     */
    int countByExample(GangGradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gang_grade
     *
     * @mbggenerated Fri Sep 14 16:12:33 CST 2018
     */
    int deleteByExample(GangGradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gang_grade
     *
     * @mbggenerated Fri Sep 14 16:12:33 CST 2018
     */
    int deleteByPrimaryKey(Integer gangId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gang_grade
     *
     * @mbggenerated Fri Sep 14 16:12:33 CST 2018
     */
    int insert(GangGrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gang_grade
     *
     * @mbggenerated Fri Sep 14 16:12:33 CST 2018
     */
    int insertSelective(GangGrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gang_grade
     *
     * @mbggenerated Fri Sep 14 16:12:33 CST 2018
     */
    List<GangGrade> selectByExample(GangGradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gang_grade
     *
     * @mbggenerated Fri Sep 14 16:12:33 CST 2018
     */
    GangGrade selectByPrimaryKey(Integer gangId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gang_grade
     *
     * @mbggenerated Fri Sep 14 16:12:33 CST 2018
     */
    int updateByExampleSelective(@Param("record") GangGrade record, @Param("example") GangGradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gang_grade
     *
     * @mbggenerated Fri Sep 14 16:12:33 CST 2018
     */
    int updateByExample(@Param("record") GangGrade record, @Param("example") GangGradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gang_grade
     *
     * @mbggenerated Fri Sep 14 16:12:33 CST 2018
     */
    int updateByPrimaryKeySelective(GangGrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gang_grade
     *
     * @mbggenerated Fri Sep 14 16:12:33 CST 2018
     */
    int updateByPrimaryKey(GangGrade record);
}