package com.chenyou.mapper;

import com.chenyou.pojo.LoginDay;
import com.chenyou.pojo.LoginDayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LoginDayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_day
     *
     * @mbggenerated Sat Sep 08 11:02:12 CST 2018
     */
    int countByExample(LoginDayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_day
     *
     * @mbggenerated Sat Sep 08 11:02:12 CST 2018
     */
    int deleteByExample(LoginDayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_day
     *
     * @mbggenerated Sat Sep 08 11:02:12 CST 2018
     */
    int deleteByPrimaryKey(Integer countDay);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_day
     *
     * @mbggenerated Sat Sep 08 11:02:12 CST 2018
     */
    int insert(LoginDay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_day
     *
     * @mbggenerated Sat Sep 08 11:02:12 CST 2018
     */
    int insertSelective(LoginDay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_day
     *
     * @mbggenerated Sat Sep 08 11:02:12 CST 2018
     */
    List<LoginDay> selectByExample(LoginDayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_day
     *
     * @mbggenerated Sat Sep 08 11:02:12 CST 2018
     */
    LoginDay selectByPrimaryKey(Integer countDay);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_day
     *
     * @mbggenerated Sat Sep 08 11:02:12 CST 2018
     */
    int updateByExampleSelective(@Param("record") LoginDay record, @Param("example") LoginDayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_day
     *
     * @mbggenerated Sat Sep 08 11:02:12 CST 2018
     */
    int updateByExample(@Param("record") LoginDay record, @Param("example") LoginDayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_day
     *
     * @mbggenerated Sat Sep 08 11:02:12 CST 2018
     */
    int updateByPrimaryKeySelective(LoginDay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_day
     *
     * @mbggenerated Sat Sep 08 11:02:12 CST 2018
     */
    int updateByPrimaryKey(LoginDay record);
}