package com.chenyou.mapper;

import com.chenyou.DataSource;
import com.chenyou.pojo.Menu;
import com.chenyou.pojo.MenuExample;
import java.util.List;
import java.util.Set;

import org.apache.ibatis.annotations.Param;
@DataSource("dataSource1")
public interface MenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Fri Aug 03 15:17:28 CST 2018
     */
    int countByExample(MenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Fri Aug 03 15:17:28 CST 2018
     */
    int deleteByExample(MenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Fri Aug 03 15:17:28 CST 2018
     */
    int deleteByPrimaryKey(Integer menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Fri Aug 03 15:17:28 CST 2018
     */
    int insert(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Fri Aug 03 15:17:28 CST 2018
     */
    int insertSelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Fri Aug 03 15:17:28 CST 2018
     */
    List<Menu> selectByExample(MenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Fri Aug 03 15:17:28 CST 2018
     */
    Menu selectByPrimaryKey(Integer menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Fri Aug 03 15:17:28 CST 2018
     */
    int updateByExampleSelective(@Param("record") Menu record, @Param("example") MenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Fri Aug 03 15:17:28 CST 2018
     */
    int updateByExample(@Param("record") Menu record, @Param("example") MenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Fri Aug 03 15:17:28 CST 2018
     */
    int updateByPrimaryKeySelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Fri Aug 03 15:17:28 CST 2018
     */
    int updateByPrimaryKey(Menu record);

    Menu checkMenuNameUnique(String menuName);

    /**
     * 根据menuId获取子菜单个数
     * @param parentId
     * @return
     */
    int countChildMenuByParentId(Integer parentId);

    /**
     *
     * @return
     */
     List<Menu> listMenu();

    /**
     * 根据角色查询菜单权限关键字
     * @param roleId
     * @return
     */
     public List<String> listMenutreePermByRoleId(Integer roleId);

    /**
     * 根据menuId查询对应的Menu
     * @param menuId
     * @return
     */
      Menu getMenuByMenuId(Integer menuId);

    /**
     * 根据父menuId查询对应的Menu
     * @param menuId
     * @return
     */
     Menu getMenuByMenuId(Long menuId);

    /**
     * 根据userId查询对应的List<Menu>
     * @param userId
     * @return
     */
     List<String> selectListMenuByUserId(Integer userId);

    /**
     * 根据menuId查询对应的权限字符串
     * @param userId
     * @return
     */
     List<Menu> listMenusByUserId(Integer userId);

     List<String> listPermsByUserId(Integer userId);


   List<Menu> listMenuByParentId(Integer parentId);
}