package com.chenyou.mapper;

import com.chenyou.pojo.OnlineplayerCount;
import com.chenyou.pojo.OnlineplayerCountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OnlineplayerCountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_onlineplayer_count
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    int countByExample(OnlineplayerCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_onlineplayer_count
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    int deleteByExample(OnlineplayerCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_onlineplayer_count
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    int deleteByPrimaryKey(Integer onlineId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_onlineplayer_count
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    int insert(OnlineplayerCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_onlineplayer_count
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    int insertSelective(OnlineplayerCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_onlineplayer_count
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    List<OnlineplayerCount> selectByExample(OnlineplayerCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_onlineplayer_count
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    OnlineplayerCount selectByPrimaryKey(Integer onlineId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_onlineplayer_count
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    int updateByExampleSelective(@Param("record") OnlineplayerCount record, @Param("example") OnlineplayerCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_onlineplayer_count
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    int updateByExample(@Param("record") OnlineplayerCount record, @Param("example") OnlineplayerCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_onlineplayer_count
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    int updateByPrimaryKeySelective(OnlineplayerCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_onlineplayer_count
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    int updateByPrimaryKey(OnlineplayerCount record);
}