package com.chenyou.mapper;

import com.chenyou.DataSource;
import com.chenyou.pojo.OpenPlan;
import com.chenyou.pojo.OpenPlanExample;
import com.chenyou.pojo.OpenPlanKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
@DataSource("dataSource2")
public interface OpenPlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_activity
     *
     * @mbggenerated Mon Jan 14 17:38:08 CST 2019
     */
    int countByExample(OpenPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_activity
     *
     * @mbggenerated Mon Jan 14 17:38:08 CST 2019
     */
    int deleteByExample(OpenPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_activity
     *
     * @mbggenerated Mon Jan 14 17:38:08 CST 2019
     */
    int deleteByPrimaryKey(OpenPlanKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_activity
     *
     * @mbggenerated Mon Jan 14 17:38:08 CST 2019
     */
    int insert(OpenPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_activity
     *
     * @mbggenerated Mon Jan 14 17:38:08 CST 2019
     */
    int insertSelective(OpenPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_activity
     *
     * @mbggenerated Mon Jan 14 17:38:08 CST 2019
     */
    List<OpenPlan> selectByExample(OpenPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_activity
     *
     * @mbggenerated Mon Jan 14 17:38:08 CST 2019
     */
    OpenPlan selectByPrimaryKey(OpenPlanKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_activity
     *
     * @mbggenerated Mon Jan 14 17:38:08 CST 2019
     */
    int updateByExampleSelective(@Param("record") OpenPlan record, @Param("example") OpenPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_activity
     *
     * @mbggenerated Mon Jan 14 17:38:08 CST 2019
     */
    int updateByExample(@Param("record") OpenPlan record, @Param("example") OpenPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_activity
     *
     * @mbggenerated Mon Jan 14 17:38:08 CST 2019
     */
    int updateByPrimaryKeySelective(OpenPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_activity
     *
     * @mbggenerated Mon Jan 14 17:38:08 CST 2019
     */
    int updateByPrimaryKey(OpenPlan record);
}