package com.chenyou.mapper;

import com.chenyou.DataSource;
import com.chenyou.pojo.PersonRank;
import com.chenyou.pojo.PersonRankExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
@DataSource("dataSource1")
public interface PersonRankMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_person_rank
     *
     * @mbggenerated Wed Oct 10 16:44:40 CST 2018
     */
    int countByExample(PersonRankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_person_rank
     *
     * @mbggenerated Wed Oct 10 16:44:40 CST 2018
     */
    int deleteByExample(PersonRankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_person_rank
     *
     * @mbggenerated Wed Oct 10 16:44:40 CST 2018
     */
    int deleteByPrimaryKey(Integer personRankId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_person_rank
     *
     * @mbggenerated Wed Oct 10 16:44:40 CST 2018
     */
    int insert(PersonRank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_person_rank
     *
     * @mbggenerated Wed Oct 10 16:44:40 CST 2018
     */
    int insertSelective(PersonRank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_person_rank
     *
     * @mbggenerated Wed Oct 10 16:44:40 CST 2018
     */
    List<PersonRank> selectByExample(PersonRankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_person_rank
     *
     * @mbggenerated Wed Oct 10 16:44:40 CST 2018
     */
    PersonRank selectByPrimaryKey(Integer personRankId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_person_rank
     *
     * @mbggenerated Wed Oct 10 16:44:40 CST 2018
     */
    int updateByExampleSelective(@Param("record") PersonRank record, @Param("example") PersonRankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_person_rank
     *
     * @mbggenerated Wed Oct 10 16:44:40 CST 2018
     */
    int updateByExample(@Param("record") PersonRank record, @Param("example") PersonRankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_person_rank
     *
     * @mbggenerated Wed Oct 10 16:44:40 CST 2018
     */
    int updateByPrimaryKeySelective(PersonRank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_person_rank
     *
     * @mbggenerated Wed Oct 10 16:44:40 CST 2018
     */
    int updateByPrimaryKey(PersonRank record);
}