package com.chenyou.mapper;

import com.chenyou.pojo.RechargeOrder;
import com.chenyou.pojo.RechargeOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RechargeOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge_order
     *
     * @mbggenerated Fri Dec 21 14:44:43 CST 2018
     */
    int countByExample(RechargeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge_order
     *
     * @mbggenerated Fri Dec 21 14:44:43 CST 2018
     */
    int deleteByExample(RechargeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge_order
     *
     * @mbggenerated Fri Dec 21 14:44:43 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge_order
     *
     * @mbggenerated Fri Dec 21 14:44:43 CST 2018
     */
    int insert(RechargeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge_order
     *
     * @mbggenerated Fri Dec 21 14:44:43 CST 2018
     */
    int insertSelective(RechargeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge_order
     *
     * @mbggenerated Fri Dec 21 14:44:43 CST 2018
     */
    List<RechargeOrder> selectByExample(RechargeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge_order
     *
     * @mbggenerated Fri Dec 21 14:44:43 CST 2018
     */
    RechargeOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge_order
     *
     * @mbggenerated Fri Dec 21 14:44:43 CST 2018
     */
    int updateByExampleSelective(@Param("record") RechargeOrder record, @Param("example") RechargeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge_order
     *
     * @mbggenerated Fri Dec 21 14:44:43 CST 2018
     */
    int updateByExample(@Param("record") RechargeOrder record, @Param("example") RechargeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge_order
     *
     * @mbggenerated Fri Dec 21 14:44:43 CST 2018
     */
    int updateByPrimaryKeySelective(RechargeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge_order
     *
     * @mbggenerated Fri Dec 21 14:44:43 CST 2018
     */
    int updateByPrimaryKey(RechargeOrder record);

    List<RechargeOrder> listRechargeOrder(@Param("start")String start,@Param("end") String end,@Param("serverId")Integer serverId);
}