package com.chenyou.pojo;

import java.util.Date;

public class ActivityOutPut {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_output.id
     *
     * @mbggenerated Mon Sep 17 14:09:43 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_output.prop_id
     *
     * @mbggenerated Mon Sep 17 14:09:43 CST 2018
     */
    private Integer propId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_output.output
     *
     * @mbggenerated Mon Sep 17 14:09:43 CST 2018
     */
    private String output;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_output.consume
     *
     * @mbggenerated Mon Sep 17 14:09:43 CST 2018
     */
    private String consume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_output.server_id
     *
     * @mbggenerated Mon Sep 17 14:09:43 CST 2018
     */
    private Integer serverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_output.server_name
     *
     * @mbggenerated Mon Sep 17 14:09:43 CST 2018
     */
    private String serverName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_output.recorde_time
     *
     * @mbggenerated Mon Sep 17 14:09:43 CST 2018
     */
    private Date recordeTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_output.id
     *
     * @return the value of t_activity_output.id
     *
     * @mbggenerated Mon Sep 17 14:09:43 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_output.id
     *
     * @param id the value for t_activity_output.id
     *
     * @mbggenerated Mon Sep 17 14:09:43 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_output.prop_id
     *
     * @return the value of t_activity_output.prop_id
     *
     * @mbggenerated Mon Sep 17 14:09:43 CST 2018
     */
    public Integer getPropId() {
        return propId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_output.prop_id
     *
     * @param propId the value for t_activity_output.prop_id
     *
     * @mbggenerated Mon Sep 17 14:09:43 CST 2018
     */
    public void setPropId(Integer propId) {
        this.propId = propId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_output.output
     *
     * @return the value of t_activity_output.output
     *
     * @mbggenerated Mon Sep 17 14:09:43 CST 2018
     */
    public String getOutput() {
        return output;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_output.output
     *
     * @param output the value for t_activity_output.output
     *
     * @mbggenerated Mon Sep 17 14:09:43 CST 2018
     */
    public void setOutput(String output) {
        this.output = output;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_output.consume
     *
     * @return the value of t_activity_output.consume
     *
     * @mbggenerated Mon Sep 17 14:09:43 CST 2018
     */
    public String getConsume() {
        return consume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_output.consume
     *
     * @param consume the value for t_activity_output.consume
     *
     * @mbggenerated Mon Sep 17 14:09:43 CST 2018
     */
    public void setConsume(String consume) {
        this.consume = consume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_output.server_id
     *
     * @return the value of t_activity_output.server_id
     *
     * @mbggenerated Mon Sep 17 14:09:43 CST 2018
     */
    public Integer getServerId() {
        return serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_output.server_id
     *
     * @param serverId the value for t_activity_output.server_id
     *
     * @mbggenerated Mon Sep 17 14:09:43 CST 2018
     */
    public void setServerId(Integer serverId) {
        this.serverId = serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_output.server_name
     *
     * @return the value of t_activity_output.server_name
     *
     * @mbggenerated Mon Sep 17 14:09:43 CST 2018
     */
    public String getServerName() {
        return serverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_output.server_name
     *
     * @param serverName the value for t_activity_output.server_name
     *
     * @mbggenerated Mon Sep 17 14:09:43 CST 2018
     */
    public void setServerName(String serverName) {
        this.serverName = serverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_output.recorde_time
     *
     * @return the value of t_activity_output.recorde_time
     *
     * @mbggenerated Mon Sep 17 14:09:43 CST 2018
     */
    public Date getRecordeTime() {
        return recordeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_output.recorde_time
     *
     * @param recordeTime the value for t_activity_output.recorde_time
     *
     * @mbggenerated Mon Sep 17 14:09:43 CST 2018
     */
    public void setRecordeTime(Date recordeTime) {
        this.recordeTime = recordeTime;
    }
}