package com.chenyou.pojo;

import java.util.Date;

public class AddNewplayer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_add_newplayer.newplayer_id
     *
     * @mbggenerated Sat Sep 08 11:02:12 CST 2018
     */
    private Integer newplayerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_add_newplayer.register_time
     *
     * @mbggenerated Sat Sep 08 11:02:12 CST 2018
     */
    private Date registerTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_add_newplayer.register_plant
     *
     * @mbggenerated Sat Sep 08 11:02:12 CST 2018
     */
    private Integer registerPlant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_add_newplayer.register_player
     *
     * @mbggenerated Sat Sep 08 11:02:12 CST 2018
     */
    private Integer registerPlayer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_add_newplayer.server_id
     *
     * @mbggenerated Sat Sep 08 11:02:12 CST 2018
     */
    private Integer serverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_add_newplayer.channel_id
     *
     * @mbggenerated Sat Sep 08 11:02:12 CST 2018
     */
    private Integer channelId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_add_newplayer.newplayer_id
     *
     * @return the value of t_add_newplayer.newplayer_id
     *
     * @mbggenerated Sat Sep 08 11:02:12 CST 2018
     */
    public Integer getNewplayerId() {
        return newplayerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_add_newplayer.newplayer_id
     *
     * @param newplayerId the value for t_add_newplayer.newplayer_id
     *
     * @mbggenerated Sat Sep 08 11:02:12 CST 2018
     */
    public void setNewplayerId(Integer newplayerId) {
        this.newplayerId = newplayerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_add_newplayer.register_time
     *
     * @return the value of t_add_newplayer.register_time
     *
     * @mbggenerated Sat Sep 08 11:02:12 CST 2018
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_add_newplayer.register_time
     *
     * @param registerTime the value for t_add_newplayer.register_time
     *
     * @mbggenerated Sat Sep 08 11:02:12 CST 2018
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_add_newplayer.register_plant
     *
     * @return the value of t_add_newplayer.register_plant
     *
     * @mbggenerated Sat Sep 08 11:02:12 CST 2018
     */
    public Integer getRegisterPlant() {
        return registerPlant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_add_newplayer.register_plant
     *
     * @param registerPlant the value for t_add_newplayer.register_plant
     *
     * @mbggenerated Sat Sep 08 11:02:12 CST 2018
     */
    public void setRegisterPlant(Integer registerPlant) {
        this.registerPlant = registerPlant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_add_newplayer.register_player
     *
     * @return the value of t_add_newplayer.register_player
     *
     * @mbggenerated Sat Sep 08 11:02:12 CST 2018
     */
    public Integer getRegisterPlayer() {
        return registerPlayer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_add_newplayer.register_player
     *
     * @param registerPlayer the value for t_add_newplayer.register_player
     *
     * @mbggenerated Sat Sep 08 11:02:12 CST 2018
     */
    public void setRegisterPlayer(Integer registerPlayer) {
        this.registerPlayer = registerPlayer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_add_newplayer.server_id
     *
     * @return the value of t_add_newplayer.server_id
     *
     * @mbggenerated Sat Sep 08 11:02:12 CST 2018
     */
    public Integer getServerId() {
        return serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_add_newplayer.server_id
     *
     * @param serverId the value for t_add_newplayer.server_id
     *
     * @mbggenerated Sat Sep 08 11:02:12 CST 2018
     */
    public void setServerId(Integer serverId) {
        this.serverId = serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_add_newplayer.channel_id
     *
     * @return the value of t_add_newplayer.channel_id
     *
     * @mbggenerated Sat Sep 08 11:02:12 CST 2018
     */
    public Integer getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_add_newplayer.channel_id
     *
     * @param channelId the value for t_add_newplayer.channel_id
     *
     * @mbggenerated Sat Sep 08 11:02:12 CST 2018
     */
    public void setChannelId(Integer channelId) {
        this.channelId = channelId;
    }

    @Override
    public String toString() {
        return "AddNewplayer{" +
                "newplayerId=" + newplayerId +
                ", registerTime=" + registerTime +
                ", registerPlant=" + registerPlant +
                ", registerPlayer=" + registerPlayer +
                ", serverId=" + serverId +
                ", channelId=" + channelId +
                '}';
    }
}