package com.chenyou.pojo;

public class AnnualPlanOpen {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_annualplan_open.id
     *
     * @mbggenerated Wed Dec 26 22:25:39 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_annualplan_open.start
     *
     * @mbggenerated Wed Dec 26 22:25:39 CST 2018
     */
    private String start;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_annualplan_open.end
     *
     * @mbggenerated Wed Dec 26 22:25:39 CST 2018
     */
    private String end;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_annualplan_open.server_id
     *
     * @mbggenerated Wed Dec 26 22:25:39 CST 2018
     */
    private Integer serverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_annualplan_open.annual_id
     *
     * @mbggenerated Wed Dec 26 22:25:39 CST 2018
     */
    private Integer annualId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_annualplan_open.template_id
     *
     * @mbggenerated Wed Dec 26 22:25:39 CST 2018
     */
    private Integer templateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_annualplan_open.status
     *
     * @mbggenerated Wed Dec 26 22:25:39 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_annualplan_open.open_time
     *
     * @mbggenerated Wed Dec 26 22:25:39 CST 2018
     */
    private String openTime;


    private String serverName;

    private String annualName;

    private String templateName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_annualplan_open.id
     *
     * @return the value of t_annualplan_open.id
     *
     * @mbggenerated Wed Dec 26 22:25:39 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_annualplan_open.id
     *
     * @param id the value for t_annualplan_open.id
     *
     * @mbggenerated Wed Dec 26 22:25:39 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_annualplan_open.start
     *
     * @return the value of t_annualplan_open.start
     *
     * @mbggenerated Wed Dec 26 22:25:39 CST 2018
     */
    public String getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_annualplan_open.start
     *
     * @param start the value for t_annualplan_open.start
     *
     * @mbggenerated Wed Dec 26 22:25:39 CST 2018
     */
    public void setStart(String start) {
        this.start = start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_annualplan_open.end
     *
     * @return the value of t_annualplan_open.end
     *
     * @mbggenerated Wed Dec 26 22:25:39 CST 2018
     */
    public String getEnd() {
        return end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_annualplan_open.end
     *
     * @param end the value for t_annualplan_open.end
     *
     * @mbggenerated Wed Dec 26 22:25:39 CST 2018
     */
    public void setEnd(String end) {
        this.end = end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_annualplan_open.server_id
     *
     * @return the value of t_annualplan_open.server_id
     *
     * @mbggenerated Wed Dec 26 22:25:39 CST 2018
     */
    public Integer getServerId() {
        return serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_annualplan_open.server_id
     *
     * @param serverId the value for t_annualplan_open.server_id
     *
     * @mbggenerated Wed Dec 26 22:25:39 CST 2018
     */
    public void setServerId(Integer serverId) {
        this.serverId = serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_annualplan_open.annual_id
     *
     * @return the value of t_annualplan_open.annual_id
     *
     * @mbggenerated Wed Dec 26 22:25:39 CST 2018
     */
    public Integer getAnnualId() {
        return annualId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_annualplan_open.annual_id
     *
     * @param annualId the value for t_annualplan_open.annual_id
     *
     * @mbggenerated Wed Dec 26 22:25:39 CST 2018
     */
    public void setAnnualId(Integer annualId) {
        this.annualId = annualId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_annualplan_open.template_id
     *
     * @return the value of t_annualplan_open.template_id
     *
     * @mbggenerated Wed Dec 26 22:25:39 CST 2018
     */
    public Integer getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_annualplan_open.template_id
     *
     * @param templateId the value for t_annualplan_open.template_id
     *
     * @mbggenerated Wed Dec 26 22:25:39 CST 2018
     */
    public void setTemplateId(Integer templateId) {
        this.templateId = templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_annualplan_open.status
     *
     * @return the value of t_annualplan_open.status
     *
     * @mbggenerated Wed Dec 26 22:25:39 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_annualplan_open.status
     *
     * @param status the value for t_annualplan_open.status
     *
     * @mbggenerated Wed Dec 26 22:25:39 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_annualplan_open.open_time
     *
     * @return the value of t_annualplan_open.open_time
     *
     * @mbggenerated Wed Dec 26 22:25:39 CST 2018
     */
    public String getOpenTime() {
        return openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_annualplan_open.open_time
     *
     * @param openTime the value for t_annualplan_open.open_time
     *
     * @mbggenerated Wed Dec 26 22:25:39 CST 2018
     */
    public void setOpenTime(String openTime) {
        this.openTime = openTime;
    }

    public String getServerName() {
        return serverName;
    }

    public void setServerName(String serverName) {
        this.serverName = serverName;
    }

    public String getAnnualName() {
        return annualName;
    }

    public void setAnnualName(String annualName) {
        this.annualName = annualName;
    }

    public String getTemplateName() {
        return templateName;
    }

    public void setTemplateName(String templateName) {
        this.templateName = templateName;
    }

    @Override
    public String toString() {
        return "AnnualPlanOpen{" + "id=" + id + ", start='" + start + '\'' + ", end='" + end + '\'' + ", serverId=" + serverId + ", annualId=" + annualId + ", templateId=" + templateId + ", status='" + status + '\'' + ", openTime='" + openTime + '\'' + ", serverName='" + serverName + '\'' + ", annualName='" + annualName + '\'' + ", templateName='" + templateName + '\'' + '}';
    }
}