package com.chenyou.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ChannelSummaryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_channel_summary
     *
     * @mbggenerated Fri Sep 21 15:02:05 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_channel_summary
     *
     * @mbggenerated Fri Sep 21 15:02:05 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_channel_summary
     *
     * @mbggenerated Fri Sep 21 15:02:05 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel_summary
     *
     * @mbggenerated Fri Sep 21 15:02:05 CST 2018
     */
    public ChannelSummaryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel_summary
     *
     * @mbggenerated Fri Sep 21 15:02:05 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel_summary
     *
     * @mbggenerated Fri Sep 21 15:02:05 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel_summary
     *
     * @mbggenerated Fri Sep 21 15:02:05 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel_summary
     *
     * @mbggenerated Fri Sep 21 15:02:05 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel_summary
     *
     * @mbggenerated Fri Sep 21 15:02:05 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel_summary
     *
     * @mbggenerated Fri Sep 21 15:02:05 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel_summary
     *
     * @mbggenerated Fri Sep 21 15:02:05 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel_summary
     *
     * @mbggenerated Fri Sep 21 15:02:05 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel_summary
     *
     * @mbggenerated Fri Sep 21 15:02:05 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel_summary
     *
     * @mbggenerated Fri Sep 21 15:02:05 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_channel_summary
     *
     * @mbggenerated Fri Sep 21 15:02:05 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andCIdIsNull() {
            addCriterion("c_id is null");
            return (Criteria) this;
        }

        public Criteria andCIdIsNotNull() {
            addCriterion("c_id is not null");
            return (Criteria) this;
        }

        public Criteria andCIdEqualTo(Integer value) {
            addCriterion("c_id =", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdNotEqualTo(Integer value) {
            addCriterion("c_id <>", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdGreaterThan(Integer value) {
            addCriterion("c_id >", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("c_id >=", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdLessThan(Integer value) {
            addCriterion("c_id <", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdLessThanOrEqualTo(Integer value) {
            addCriterion("c_id <=", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdIn(List<Integer> values) {
            addCriterion("c_id in", values, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdNotIn(List<Integer> values) {
            addCriterion("c_id not in", values, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdBetween(Integer value1, Integer value2) {
            addCriterion("c_id between", value1, value2, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdNotBetween(Integer value1, Integer value2) {
            addCriterion("c_id not between", value1, value2, "cId");
            return (Criteria) this;
        }

        public Criteria andChannelIdIsNull() {
            addCriterion("channel_id is null");
            return (Criteria) this;
        }

        public Criteria andChannelIdIsNotNull() {
            addCriterion("channel_id is not null");
            return (Criteria) this;
        }

        public Criteria andChannelIdEqualTo(Integer value) {
            addCriterion("channel_id =", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdNotEqualTo(Integer value) {
            addCriterion("channel_id <>", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdGreaterThan(Integer value) {
            addCriterion("channel_id >", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("channel_id >=", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdLessThan(Integer value) {
            addCriterion("channel_id <", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdLessThanOrEqualTo(Integer value) {
            addCriterion("channel_id <=", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdIn(List<Integer> values) {
            addCriterion("channel_id in", values, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdNotIn(List<Integer> values) {
            addCriterion("channel_id not in", values, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdBetween(Integer value1, Integer value2) {
            addCriterion("channel_id between", value1, value2, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdNotBetween(Integer value1, Integer value2) {
            addCriterion("channel_id not between", value1, value2, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelNameIsNull() {
            addCriterion("channel_name is null");
            return (Criteria) this;
        }

        public Criteria andChannelNameIsNotNull() {
            addCriterion("channel_name is not null");
            return (Criteria) this;
        }

        public Criteria andChannelNameEqualTo(String value) {
            addCriterion("channel_name =", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameNotEqualTo(String value) {
            addCriterion("channel_name <>", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameGreaterThan(String value) {
            addCriterion("channel_name >", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameGreaterThanOrEqualTo(String value) {
            addCriterion("channel_name >=", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameLessThan(String value) {
            addCriterion("channel_name <", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameLessThanOrEqualTo(String value) {
            addCriterion("channel_name <=", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameLike(String value) {
            addCriterion("channel_name like", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameNotLike(String value) {
            addCriterion("channel_name not like", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameIn(List<String> values) {
            addCriterion("channel_name in", values, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameNotIn(List<String> values) {
            addCriterion("channel_name not in", values, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameBetween(String value1, String value2) {
            addCriterion("channel_name between", value1, value2, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameNotBetween(String value1, String value2) {
            addCriterion("channel_name not between", value1, value2, "channelName");
            return (Criteria) this;
        }

        public Criteria andActivatePlayerIsNull() {
            addCriterion("activate_player is null");
            return (Criteria) this;
        }

        public Criteria andActivatePlayerIsNotNull() {
            addCriterion("activate_player is not null");
            return (Criteria) this;
        }

        public Criteria andActivatePlayerEqualTo(Integer value) {
            addCriterion("activate_player =", value, "activatePlayer");
            return (Criteria) this;
        }

        public Criteria andActivatePlayerNotEqualTo(Integer value) {
            addCriterion("activate_player <>", value, "activatePlayer");
            return (Criteria) this;
        }

        public Criteria andActivatePlayerGreaterThan(Integer value) {
            addCriterion("activate_player >", value, "activatePlayer");
            return (Criteria) this;
        }

        public Criteria andActivatePlayerGreaterThanOrEqualTo(Integer value) {
            addCriterion("activate_player >=", value, "activatePlayer");
            return (Criteria) this;
        }

        public Criteria andActivatePlayerLessThan(Integer value) {
            addCriterion("activate_player <", value, "activatePlayer");
            return (Criteria) this;
        }

        public Criteria andActivatePlayerLessThanOrEqualTo(Integer value) {
            addCriterion("activate_player <=", value, "activatePlayer");
            return (Criteria) this;
        }

        public Criteria andActivatePlayerIn(List<Integer> values) {
            addCriterion("activate_player in", values, "activatePlayer");
            return (Criteria) this;
        }

        public Criteria andActivatePlayerNotIn(List<Integer> values) {
            addCriterion("activate_player not in", values, "activatePlayer");
            return (Criteria) this;
        }

        public Criteria andActivatePlayerBetween(Integer value1, Integer value2) {
            addCriterion("activate_player between", value1, value2, "activatePlayer");
            return (Criteria) this;
        }

        public Criteria andActivatePlayerNotBetween(Integer value1, Integer value2) {
            addCriterion("activate_player not between", value1, value2, "activatePlayer");
            return (Criteria) this;
        }

        public Criteria andRegisterPlayerIsNull() {
            addCriterion("register_player is null");
            return (Criteria) this;
        }

        public Criteria andRegisterPlayerIsNotNull() {
            addCriterion("register_player is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterPlayerEqualTo(Integer value) {
            addCriterion("register_player =", value, "registerPlayer");
            return (Criteria) this;
        }

        public Criteria andRegisterPlayerNotEqualTo(Integer value) {
            addCriterion("register_player <>", value, "registerPlayer");
            return (Criteria) this;
        }

        public Criteria andRegisterPlayerGreaterThan(Integer value) {
            addCriterion("register_player >", value, "registerPlayer");
            return (Criteria) this;
        }

        public Criteria andRegisterPlayerGreaterThanOrEqualTo(Integer value) {
            addCriterion("register_player >=", value, "registerPlayer");
            return (Criteria) this;
        }

        public Criteria andRegisterPlayerLessThan(Integer value) {
            addCriterion("register_player <", value, "registerPlayer");
            return (Criteria) this;
        }

        public Criteria andRegisterPlayerLessThanOrEqualTo(Integer value) {
            addCriterion("register_player <=", value, "registerPlayer");
            return (Criteria) this;
        }

        public Criteria andRegisterPlayerIn(List<Integer> values) {
            addCriterion("register_player in", values, "registerPlayer");
            return (Criteria) this;
        }

        public Criteria andRegisterPlayerNotIn(List<Integer> values) {
            addCriterion("register_player not in", values, "registerPlayer");
            return (Criteria) this;
        }

        public Criteria andRegisterPlayerBetween(Integer value1, Integer value2) {
            addCriterion("register_player between", value1, value2, "registerPlayer");
            return (Criteria) this;
        }

        public Criteria andRegisterPlayerNotBetween(Integer value1, Integer value2) {
            addCriterion("register_player not between", value1, value2, "registerPlayer");
            return (Criteria) this;
        }

        public Criteria andActivePlayerIsNull() {
            addCriterion("active_player is null");
            return (Criteria) this;
        }

        public Criteria andActivePlayerIsNotNull() {
            addCriterion("active_player is not null");
            return (Criteria) this;
        }

        public Criteria andActivePlayerEqualTo(Integer value) {
            addCriterion("active_player =", value, "activePlayer");
            return (Criteria) this;
        }

        public Criteria andActivePlayerNotEqualTo(Integer value) {
            addCriterion("active_player <>", value, "activePlayer");
            return (Criteria) this;
        }

        public Criteria andActivePlayerGreaterThan(Integer value) {
            addCriterion("active_player >", value, "activePlayer");
            return (Criteria) this;
        }

        public Criteria andActivePlayerGreaterThanOrEqualTo(Integer value) {
            addCriterion("active_player >=", value, "activePlayer");
            return (Criteria) this;
        }

        public Criteria andActivePlayerLessThan(Integer value) {
            addCriterion("active_player <", value, "activePlayer");
            return (Criteria) this;
        }

        public Criteria andActivePlayerLessThanOrEqualTo(Integer value) {
            addCriterion("active_player <=", value, "activePlayer");
            return (Criteria) this;
        }

        public Criteria andActivePlayerIn(List<Integer> values) {
            addCriterion("active_player in", values, "activePlayer");
            return (Criteria) this;
        }

        public Criteria andActivePlayerNotIn(List<Integer> values) {
            addCriterion("active_player not in", values, "activePlayer");
            return (Criteria) this;
        }

        public Criteria andActivePlayerBetween(Integer value1, Integer value2) {
            addCriterion("active_player between", value1, value2, "activePlayer");
            return (Criteria) this;
        }

        public Criteria andActivePlayerNotBetween(Integer value1, Integer value2) {
            addCriterion("active_player not between", value1, value2, "activePlayer");
            return (Criteria) this;
        }

        public Criteria andRechargePlayerIsNull() {
            addCriterion("recharge_player is null");
            return (Criteria) this;
        }

        public Criteria andRechargePlayerIsNotNull() {
            addCriterion("recharge_player is not null");
            return (Criteria) this;
        }

        public Criteria andRechargePlayerEqualTo(Integer value) {
            addCriterion("recharge_player =", value, "rechargePlayer");
            return (Criteria) this;
        }

        public Criteria andRechargePlayerNotEqualTo(Integer value) {
            addCriterion("recharge_player <>", value, "rechargePlayer");
            return (Criteria) this;
        }

        public Criteria andRechargePlayerGreaterThan(Integer value) {
            addCriterion("recharge_player >", value, "rechargePlayer");
            return (Criteria) this;
        }

        public Criteria andRechargePlayerGreaterThanOrEqualTo(Integer value) {
            addCriterion("recharge_player >=", value, "rechargePlayer");
            return (Criteria) this;
        }

        public Criteria andRechargePlayerLessThan(Integer value) {
            addCriterion("recharge_player <", value, "rechargePlayer");
            return (Criteria) this;
        }

        public Criteria andRechargePlayerLessThanOrEqualTo(Integer value) {
            addCriterion("recharge_player <=", value, "rechargePlayer");
            return (Criteria) this;
        }

        public Criteria andRechargePlayerIn(List<Integer> values) {
            addCriterion("recharge_player in", values, "rechargePlayer");
            return (Criteria) this;
        }

        public Criteria andRechargePlayerNotIn(List<Integer> values) {
            addCriterion("recharge_player not in", values, "rechargePlayer");
            return (Criteria) this;
        }

        public Criteria andRechargePlayerBetween(Integer value1, Integer value2) {
            addCriterion("recharge_player between", value1, value2, "rechargePlayer");
            return (Criteria) this;
        }

        public Criteria andRechargePlayerNotBetween(Integer value1, Integer value2) {
            addCriterion("recharge_player not between", value1, value2, "rechargePlayer");
            return (Criteria) this;
        }

        public Criteria andTimeLeaveIsNull() {
            addCriterion("time_leave is null");
            return (Criteria) this;
        }

        public Criteria andTimeLeaveIsNotNull() {
            addCriterion("time_leave is not null");
            return (Criteria) this;
        }

        public Criteria andTimeLeaveEqualTo(String value) {
            addCriterion("time_leave =", value, "timeLeave");
            return (Criteria) this;
        }

        public Criteria andTimeLeaveNotEqualTo(String value) {
            addCriterion("time_leave <>", value, "timeLeave");
            return (Criteria) this;
        }

        public Criteria andTimeLeaveGreaterThan(String value) {
            addCriterion("time_leave >", value, "timeLeave");
            return (Criteria) this;
        }

        public Criteria andTimeLeaveGreaterThanOrEqualTo(String value) {
            addCriterion("time_leave >=", value, "timeLeave");
            return (Criteria) this;
        }

        public Criteria andTimeLeaveLessThan(String value) {
            addCriterion("time_leave <", value, "timeLeave");
            return (Criteria) this;
        }

        public Criteria andTimeLeaveLessThanOrEqualTo(String value) {
            addCriterion("time_leave <=", value, "timeLeave");
            return (Criteria) this;
        }

        public Criteria andTimeLeaveLike(String value) {
            addCriterion("time_leave like", value, "timeLeave");
            return (Criteria) this;
        }

        public Criteria andTimeLeaveNotLike(String value) {
            addCriterion("time_leave not like", value, "timeLeave");
            return (Criteria) this;
        }

        public Criteria andTimeLeaveIn(List<String> values) {
            addCriterion("time_leave in", values, "timeLeave");
            return (Criteria) this;
        }

        public Criteria andTimeLeaveNotIn(List<String> values) {
            addCriterion("time_leave not in", values, "timeLeave");
            return (Criteria) this;
        }

        public Criteria andTimeLeaveBetween(String value1, String value2) {
            addCriterion("time_leave between", value1, value2, "timeLeave");
            return (Criteria) this;
        }

        public Criteria andTimeLeaveNotBetween(String value1, String value2) {
            addCriterion("time_leave not between", value1, value2, "timeLeave");
            return (Criteria) this;
        }

        public Criteria andThreedayLeaveIsNull() {
            addCriterion("threeday_leave is null");
            return (Criteria) this;
        }

        public Criteria andThreedayLeaveIsNotNull() {
            addCriterion("threeday_leave is not null");
            return (Criteria) this;
        }

        public Criteria andThreedayLeaveEqualTo(String value) {
            addCriterion("threeday_leave =", value, "threedayLeave");
            return (Criteria) this;
        }

        public Criteria andThreedayLeaveNotEqualTo(String value) {
            addCriterion("threeday_leave <>", value, "threedayLeave");
            return (Criteria) this;
        }

        public Criteria andThreedayLeaveGreaterThan(String value) {
            addCriterion("threeday_leave >", value, "threedayLeave");
            return (Criteria) this;
        }

        public Criteria andThreedayLeaveGreaterThanOrEqualTo(String value) {
            addCriterion("threeday_leave >=", value, "threedayLeave");
            return (Criteria) this;
        }

        public Criteria andThreedayLeaveLessThan(String value) {
            addCriterion("threeday_leave <", value, "threedayLeave");
            return (Criteria) this;
        }

        public Criteria andThreedayLeaveLessThanOrEqualTo(String value) {
            addCriterion("threeday_leave <=", value, "threedayLeave");
            return (Criteria) this;
        }

        public Criteria andThreedayLeaveLike(String value) {
            addCriterion("threeday_leave like", value, "threedayLeave");
            return (Criteria) this;
        }

        public Criteria andThreedayLeaveNotLike(String value) {
            addCriterion("threeday_leave not like", value, "threedayLeave");
            return (Criteria) this;
        }

        public Criteria andThreedayLeaveIn(List<String> values) {
            addCriterion("threeday_leave in", values, "threedayLeave");
            return (Criteria) this;
        }

        public Criteria andThreedayLeaveNotIn(List<String> values) {
            addCriterion("threeday_leave not in", values, "threedayLeave");
            return (Criteria) this;
        }

        public Criteria andThreedayLeaveBetween(String value1, String value2) {
            addCriterion("threeday_leave between", value1, value2, "threedayLeave");
            return (Criteria) this;
        }

        public Criteria andThreedayLeaveNotBetween(String value1, String value2) {
            addCriterion("threeday_leave not between", value1, value2, "threedayLeave");
            return (Criteria) this;
        }

        public Criteria andSevendayLeaveIsNull() {
            addCriterion("sevenday_leave is null");
            return (Criteria) this;
        }

        public Criteria andSevendayLeaveIsNotNull() {
            addCriterion("sevenday_leave is not null");
            return (Criteria) this;
        }

        public Criteria andSevendayLeaveEqualTo(String value) {
            addCriterion("sevenday_leave =", value, "sevendayLeave");
            return (Criteria) this;
        }

        public Criteria andSevendayLeaveNotEqualTo(String value) {
            addCriterion("sevenday_leave <>", value, "sevendayLeave");
            return (Criteria) this;
        }

        public Criteria andSevendayLeaveGreaterThan(String value) {
            addCriterion("sevenday_leave >", value, "sevendayLeave");
            return (Criteria) this;
        }

        public Criteria andSevendayLeaveGreaterThanOrEqualTo(String value) {
            addCriterion("sevenday_leave >=", value, "sevendayLeave");
            return (Criteria) this;
        }

        public Criteria andSevendayLeaveLessThan(String value) {
            addCriterion("sevenday_leave <", value, "sevendayLeave");
            return (Criteria) this;
        }

        public Criteria andSevendayLeaveLessThanOrEqualTo(String value) {
            addCriterion("sevenday_leave <=", value, "sevendayLeave");
            return (Criteria) this;
        }

        public Criteria andSevendayLeaveLike(String value) {
            addCriterion("sevenday_leave like", value, "sevendayLeave");
            return (Criteria) this;
        }

        public Criteria andSevendayLeaveNotLike(String value) {
            addCriterion("sevenday_leave not like", value, "sevendayLeave");
            return (Criteria) this;
        }

        public Criteria andSevendayLeaveIn(List<String> values) {
            addCriterion("sevenday_leave in", values, "sevendayLeave");
            return (Criteria) this;
        }

        public Criteria andSevendayLeaveNotIn(List<String> values) {
            addCriterion("sevenday_leave not in", values, "sevendayLeave");
            return (Criteria) this;
        }

        public Criteria andSevendayLeaveBetween(String value1, String value2) {
            addCriterion("sevenday_leave between", value1, value2, "sevendayLeave");
            return (Criteria) this;
        }

        public Criteria andSevendayLeaveNotBetween(String value1, String value2) {
            addCriterion("sevenday_leave not between", value1, value2, "sevendayLeave");
            return (Criteria) this;
        }

        public Criteria andPayRateIsNull() {
            addCriterion("pay_rate is null");
            return (Criteria) this;
        }

        public Criteria andPayRateIsNotNull() {
            addCriterion("pay_rate is not null");
            return (Criteria) this;
        }

        public Criteria andPayRateEqualTo(String value) {
            addCriterion("pay_rate =", value, "payRate");
            return (Criteria) this;
        }

        public Criteria andPayRateNotEqualTo(String value) {
            addCriterion("pay_rate <>", value, "payRate");
            return (Criteria) this;
        }

        public Criteria andPayRateGreaterThan(String value) {
            addCriterion("pay_rate >", value, "payRate");
            return (Criteria) this;
        }

        public Criteria andPayRateGreaterThanOrEqualTo(String value) {
            addCriterion("pay_rate >=", value, "payRate");
            return (Criteria) this;
        }

        public Criteria andPayRateLessThan(String value) {
            addCriterion("pay_rate <", value, "payRate");
            return (Criteria) this;
        }

        public Criteria andPayRateLessThanOrEqualTo(String value) {
            addCriterion("pay_rate <=", value, "payRate");
            return (Criteria) this;
        }

        public Criteria andPayRateLike(String value) {
            addCriterion("pay_rate like", value, "payRate");
            return (Criteria) this;
        }

        public Criteria andPayRateNotLike(String value) {
            addCriterion("pay_rate not like", value, "payRate");
            return (Criteria) this;
        }

        public Criteria andPayRateIn(List<String> values) {
            addCriterion("pay_rate in", values, "payRate");
            return (Criteria) this;
        }

        public Criteria andPayRateNotIn(List<String> values) {
            addCriterion("pay_rate not in", values, "payRate");
            return (Criteria) this;
        }

        public Criteria andPayRateBetween(String value1, String value2) {
            addCriterion("pay_rate between", value1, value2, "payRate");
            return (Criteria) this;
        }

        public Criteria andPayRateNotBetween(String value1, String value2) {
            addCriterion("pay_rate not between", value1, value2, "payRate");
            return (Criteria) this;
        }

        public Criteria andRechargeMoneyIsNull() {
            addCriterion("recharge_money is null");
            return (Criteria) this;
        }

        public Criteria andRechargeMoneyIsNotNull() {
            addCriterion("recharge_money is not null");
            return (Criteria) this;
        }

        public Criteria andRechargeMoneyEqualTo(Integer value) {
            addCriterion("recharge_money =", value, "rechargeMoney");
            return (Criteria) this;
        }

        public Criteria andRechargeMoneyNotEqualTo(Integer value) {
            addCriterion("recharge_money <>", value, "rechargeMoney");
            return (Criteria) this;
        }

        public Criteria andRechargeMoneyGreaterThan(Integer value) {
            addCriterion("recharge_money >", value, "rechargeMoney");
            return (Criteria) this;
        }

        public Criteria andRechargeMoneyGreaterThanOrEqualTo(Integer value) {
            addCriterion("recharge_money >=", value, "rechargeMoney");
            return (Criteria) this;
        }

        public Criteria andRechargeMoneyLessThan(Integer value) {
            addCriterion("recharge_money <", value, "rechargeMoney");
            return (Criteria) this;
        }

        public Criteria andRechargeMoneyLessThanOrEqualTo(Integer value) {
            addCriterion("recharge_money <=", value, "rechargeMoney");
            return (Criteria) this;
        }

        public Criteria andRechargeMoneyIn(List<Integer> values) {
            addCriterion("recharge_money in", values, "rechargeMoney");
            return (Criteria) this;
        }

        public Criteria andRechargeMoneyNotIn(List<Integer> values) {
            addCriterion("recharge_money not in", values, "rechargeMoney");
            return (Criteria) this;
        }

        public Criteria andRechargeMoneyBetween(Integer value1, Integer value2) {
            addCriterion("recharge_money between", value1, value2, "rechargeMoney");
            return (Criteria) this;
        }

        public Criteria andRechargeMoneyNotBetween(Integer value1, Integer value2) {
            addCriterion("recharge_money not between", value1, value2, "rechargeMoney");
            return (Criteria) this;
        }

        public Criteria andPayApIsNull() {
            addCriterion("pay_ap is null");
            return (Criteria) this;
        }

        public Criteria andPayApIsNotNull() {
            addCriterion("pay_ap is not null");
            return (Criteria) this;
        }

        public Criteria andPayApEqualTo(Double value) {
            addCriterion("pay_ap =", value, "payAp");
            return (Criteria) this;
        }

        public Criteria andPayApNotEqualTo(Double value) {
            addCriterion("pay_ap <>", value, "payAp");
            return (Criteria) this;
        }

        public Criteria andPayApGreaterThan(Double value) {
            addCriterion("pay_ap >", value, "payAp");
            return (Criteria) this;
        }

        public Criteria andPayApGreaterThanOrEqualTo(Double value) {
            addCriterion("pay_ap >=", value, "payAp");
            return (Criteria) this;
        }

        public Criteria andPayApLessThan(Double value) {
            addCriterion("pay_ap <", value, "payAp");
            return (Criteria) this;
        }

        public Criteria andPayApLessThanOrEqualTo(Double value) {
            addCriterion("pay_ap <=", value, "payAp");
            return (Criteria) this;
        }

        public Criteria andPayApIn(List<Double> values) {
            addCriterion("pay_ap in", values, "payAp");
            return (Criteria) this;
        }

        public Criteria andPayApNotIn(List<Double> values) {
            addCriterion("pay_ap not in", values, "payAp");
            return (Criteria) this;
        }

        public Criteria andPayApBetween(Double value1, Double value2) {
            addCriterion("pay_ap between", value1, value2, "payAp");
            return (Criteria) this;
        }

        public Criteria andPayApNotBetween(Double value1, Double value2) {
            addCriterion("pay_ap not between", value1, value2, "payAp");
            return (Criteria) this;
        }

        public Criteria andRegisterApIsNull() {
            addCriterion("register_ap is null");
            return (Criteria) this;
        }

        public Criteria andRegisterApIsNotNull() {
            addCriterion("register_ap is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterApEqualTo(Double value) {
            addCriterion("register_ap =", value, "registerAp");
            return (Criteria) this;
        }

        public Criteria andRegisterApNotEqualTo(Double value) {
            addCriterion("register_ap <>", value, "registerAp");
            return (Criteria) this;
        }

        public Criteria andRegisterApGreaterThan(Double value) {
            addCriterion("register_ap >", value, "registerAp");
            return (Criteria) this;
        }

        public Criteria andRegisterApGreaterThanOrEqualTo(Double value) {
            addCriterion("register_ap >=", value, "registerAp");
            return (Criteria) this;
        }

        public Criteria andRegisterApLessThan(Double value) {
            addCriterion("register_ap <", value, "registerAp");
            return (Criteria) this;
        }

        public Criteria andRegisterApLessThanOrEqualTo(Double value) {
            addCriterion("register_ap <=", value, "registerAp");
            return (Criteria) this;
        }

        public Criteria andRegisterApIn(List<Double> values) {
            addCriterion("register_ap in", values, "registerAp");
            return (Criteria) this;
        }

        public Criteria andRegisterApNotIn(List<Double> values) {
            addCriterion("register_ap not in", values, "registerAp");
            return (Criteria) this;
        }

        public Criteria andRegisterApBetween(Double value1, Double value2) {
            addCriterion("register_ap between", value1, value2, "registerAp");
            return (Criteria) this;
        }

        public Criteria andRegisterApNotBetween(Double value1, Double value2) {
            addCriterion("register_ap not between", value1, value2, "registerAp");
            return (Criteria) this;
        }

        public Criteria andShowTimeIsNull() {
            addCriterion("show_time is null");
            return (Criteria) this;
        }

        public Criteria andShowTimeIsNotNull() {
            addCriterion("show_time is not null");
            return (Criteria) this;
        }

        public Criteria andShowTimeEqualTo(Date value) {
            addCriterionForJDBCDate("show_time =", value, "showTime");
            return (Criteria) this;
        }

        public Criteria andShowTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("show_time <>", value, "showTime");
            return (Criteria) this;
        }

        public Criteria andShowTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("show_time >", value, "showTime");
            return (Criteria) this;
        }

        public Criteria andShowTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("show_time >=", value, "showTime");
            return (Criteria) this;
        }

        public Criteria andShowTimeLessThan(Date value) {
            addCriterionForJDBCDate("show_time <", value, "showTime");
            return (Criteria) this;
        }

        public Criteria andShowTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("show_time <=", value, "showTime");
            return (Criteria) this;
        }

        public Criteria andShowTimeIn(List<Date> values) {
            addCriterionForJDBCDate("show_time in", values, "showTime");
            return (Criteria) this;
        }

        public Criteria andShowTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("show_time not in", values, "showTime");
            return (Criteria) this;
        }

        public Criteria andShowTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("show_time between", value1, value2, "showTime");
            return (Criteria) this;
        }

        public Criteria andShowTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("show_time not between", value1, value2, "showTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_channel_summary
     *
     * @mbggenerated do_not_delete_during_merge Fri Sep 21 15:02:05 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_channel_summary
     *
     * @mbggenerated Fri Sep 21 15:02:05 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}