package com.chenyou.pojo;

public class Channel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_channel.channel_id
     *
     * @mbggenerated Mon Oct 08 16:56:43 CST 2018
     */
    private String channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_channel.channel_name
     *
     * @mbggenerated Mon Oct 08 16:56:43 CST 2018
     */
    private String channelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_channel.server_id
     *
     * @mbggenerated Mon Oct 08 16:56:43 CST 2018
     */
    private Integer serverId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_channel.channel_id
     *
     * @return the value of t_channel.channel_id
     *
     * @mbggenerated Mon Oct 08 16:56:43 CST 2018
     */
    public String getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_channel.channel_id
     *
     * @param channelId the value for t_channel.channel_id
     *
     * @mbggenerated Mon Oct 08 16:56:43 CST 2018
     */
    public void setChannelId(String channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_channel.channel_name
     *
     * @return the value of t_channel.channel_name
     *
     * @mbggenerated Mon Oct 08 16:56:43 CST 2018
     */
    public String getChannelName() {
        return channelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_channel.channel_name
     *
     * @param channelName the value for t_channel.channel_name
     *
     * @mbggenerated Mon Oct 08 16:56:43 CST 2018
     */
    public void setChannelName(String channelName) {
        this.channelName = channelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_channel.server_id
     *
     * @return the value of t_channel.server_id
     *
     * @mbggenerated Mon Oct 08 16:56:43 CST 2018
     */
    public Integer getServerId() {
        return serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_channel.server_id
     *
     * @param serverId the value for t_channel.server_id
     *
     * @mbggenerated Mon Oct 08 16:56:43 CST 2018
     */
    public void setServerId(Integer serverId) {
        this.serverId = serverId;
    }
}