package com.chenyou.pojo;

public class GangGrade {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gang_grade.gang_id
     *
     * @mbggenerated Wed Oct 10 11:13:33 CST 2018
     */
    private Integer gangId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gang_grade.gang_grade
     *
     * @mbggenerated Wed Oct 10 11:13:33 CST 2018
     */
    private Integer gangGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gang_grade.gang_count
     *
     * @mbggenerated Wed Oct 10 11:13:33 CST 2018
     */
    private Integer gangCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gang_grade.server_id
     *
     * @mbggenerated Wed Oct 10 11:13:33 CST 2018
     */
    private Integer serverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gang_grade.channel_id
     *
     * @mbggenerated Wed Oct 10 11:13:33 CST 2018
     */
    private String channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gang_grade.show_time
     *
     * @mbggenerated Wed Oct 10 11:13:33 CST 2018
     */
    private String showTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gang_grade.gang_id
     *
     * @return the value of t_gang_grade.gang_id
     *
     * @mbggenerated Wed Oct 10 11:13:33 CST 2018
     */
    public Integer getGangId() {
        return gangId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gang_grade.gang_id
     *
     * @param gangId the value for t_gang_grade.gang_id
     *
     * @mbggenerated Wed Oct 10 11:13:33 CST 2018
     */
    public void setGangId(Integer gangId) {
        this.gangId = gangId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gang_grade.gang_grade
     *
     * @return the value of t_gang_grade.gang_grade
     *
     * @mbggenerated Wed Oct 10 11:13:33 CST 2018
     */
    public Integer getGangGrade() {
        return gangGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gang_grade.gang_grade
     *
     * @param gangGrade the value for t_gang_grade.gang_grade
     *
     * @mbggenerated Wed Oct 10 11:13:33 CST 2018
     */
    public void setGangGrade(Integer gangGrade) {
        this.gangGrade = gangGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gang_grade.gang_count
     *
     * @return the value of t_gang_grade.gang_count
     *
     * @mbggenerated Wed Oct 10 11:13:33 CST 2018
     */
    public Integer getGangCount() {
        return gangCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gang_grade.gang_count
     *
     * @param gangCount the value for t_gang_grade.gang_count
     *
     * @mbggenerated Wed Oct 10 11:13:33 CST 2018
     */
    public void setGangCount(Integer gangCount) {
        this.gangCount = gangCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gang_grade.server_id
     *
     * @return the value of t_gang_grade.server_id
     *
     * @mbggenerated Wed Oct 10 11:13:33 CST 2018
     */
    public Integer getServerId() {
        return serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gang_grade.server_id
     *
     * @param serverId the value for t_gang_grade.server_id
     *
     * @mbggenerated Wed Oct 10 11:13:33 CST 2018
     */
    public void setServerId(Integer serverId) {
        this.serverId = serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gang_grade.channel_id
     *
     * @return the value of t_gang_grade.channel_id
     *
     * @mbggenerated Wed Oct 10 11:13:33 CST 2018
     */
    public String getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gang_grade.channel_id
     *
     * @param channelId the value for t_gang_grade.channel_id
     *
     * @mbggenerated Wed Oct 10 11:13:33 CST 2018
     */
    public void setChannelId(String channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gang_grade.show_time
     *
     * @return the value of t_gang_grade.show_time
     *
     * @mbggenerated Wed Oct 10 11:13:33 CST 2018
     */
    public String getShowTime() {
        return showTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gang_grade.show_time
     *
     * @param showTime the value for t_gang_grade.show_time
     *
     * @mbggenerated Wed Oct 10 11:13:33 CST 2018
     */
    public void setShowTime(String showTime) {
        this.showTime = showTime;
    }

    @Override
    public String toString() {
        return "GangGrade{" +
                "gangId=" + gangId +
                ", gangGrade=" + gangGrade +
                ", gangCount=" + gangCount +
                ", serverId=" + serverId +
                ", channelId='" + channelId + '\'' +
                ", showTime='" + showTime + '\'' +
                '}';
    }
}