package com.chenyou.pojo;

public class GradePlayer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_grade_player.grade_id
     *
     * @mbggenerated Wed Oct 10 10:40:50 CST 2018
     */
    private Integer gradeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_grade_player.grade_section
     *
     * @mbggenerated Wed Oct 10 10:40:50 CST 2018
     */
    private String gradeSection;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_grade_player.grade_player
     *
     * @mbggenerated Wed Oct 10 10:40:50 CST 2018
     */
    private Integer gradePlayer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_grade_player.server_id
     *
     * @mbggenerated Wed Oct 10 10:40:50 CST 2018
     */
    private Integer serverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_grade_player.channel_id
     *
     * @mbggenerated Wed Oct 10 10:40:50 CST 2018
     */
    private String channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_grade_player.show_time
     *
     * @mbggenerated Wed Oct 10 10:40:50 CST 2018
     */
    private String showTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_grade_player.grade_id
     *
     * @return the value of t_grade_player.grade_id
     *
     * @mbggenerated Wed Oct 10 10:40:50 CST 2018
     */
    public Integer getGradeId() {
        return gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_grade_player.grade_id
     *
     * @param gradeId the value for t_grade_player.grade_id
     *
     * @mbggenerated Wed Oct 10 10:40:50 CST 2018
     */
    public void setGradeId(Integer gradeId) {
        this.gradeId = gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_grade_player.grade_section
     *
     * @return the value of t_grade_player.grade_section
     *
     * @mbggenerated Wed Oct 10 10:40:50 CST 2018
     */
    public String getGradeSection() {
        return gradeSection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_grade_player.grade_section
     *
     * @param gradeSection the value for t_grade_player.grade_section
     *
     * @mbggenerated Wed Oct 10 10:40:50 CST 2018
     */
    public void setGradeSection(String gradeSection) {
        this.gradeSection = gradeSection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_grade_player.grade_player
     *
     * @return the value of t_grade_player.grade_player
     *
     * @mbggenerated Wed Oct 10 10:40:50 CST 2018
     */
    public Integer getGradePlayer() {
        return gradePlayer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_grade_player.grade_player
     *
     * @param gradePlayer the value for t_grade_player.grade_player
     *
     * @mbggenerated Wed Oct 10 10:40:50 CST 2018
     */
    public void setGradePlayer(Integer gradePlayer) {
        this.gradePlayer = gradePlayer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_grade_player.server_id
     *
     * @return the value of t_grade_player.server_id
     *
     * @mbggenerated Wed Oct 10 10:40:50 CST 2018
     */
    public Integer getServerId() {
        return serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_grade_player.server_id
     *
     * @param serverId the value for t_grade_player.server_id
     *
     * @mbggenerated Wed Oct 10 10:40:50 CST 2018
     */
    public void setServerId(Integer serverId) {
        this.serverId = serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_grade_player.channel_id
     *
     * @return the value of t_grade_player.channel_id
     *
     * @mbggenerated Wed Oct 10 10:40:50 CST 2018
     */
    public String getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_grade_player.channel_id
     *
     * @param channelId the value for t_grade_player.channel_id
     *
     * @mbggenerated Wed Oct 10 10:40:50 CST 2018
     */
    public void setChannelId(String channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_grade_player.show_time
     *
     * @return the value of t_grade_player.show_time
     *
     * @mbggenerated Wed Oct 10 10:40:50 CST 2018
     */
    public String getShowTime() {
        return showTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_grade_player.show_time
     *
     * @param showTime the value for t_grade_player.show_time
     *
     * @mbggenerated Wed Oct 10 10:40:50 CST 2018
     */
    public void setShowTime(String showTime) {
        this.showTime = showTime;
    }

    @Override
    public String toString() {
        return "GradePlayer{" +
                "gradeId=" + gradeId +
                ", gradeSection='" + gradeSection + '\'' +
                ", gradePlayer=" + gradePlayer +
                ", serverId=" + serverId +
                ", channelId='" + channelId + '\'' +
                ", showTime='" + showTime + '\'' +
                '}';
    }
}