package com.chenyou.pojo;

import java.util.Date;

public class IncomeClass {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income_class.in_id
     *
     * @mbggenerated Thu Sep 13 18:01:17 CST 2018
     */
    private Integer inId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income_class.pay_ap
     *
     * @mbggenerated Thu Sep 13 18:01:17 CST 2018
     */
    private Double payAp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income_class.add_ap
     *
     * @mbggenerated Thu Sep 13 18:01:17 CST 2018
     */
    private Double addAp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income_class.day_income
     *
     * @mbggenerated Thu Sep 13 18:01:17 CST 2018
     */
    private Integer dayIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income_class.day_payrate
     *
     * @mbggenerated Thu Sep 13 18:01:17 CST 2018
     */
    private String dayPayrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income_class.add_rate_user
     *
     * @mbggenerated Thu Sep 13 18:01:17 CST 2018
     */
    private Integer addRateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income_class.count_rate_user
     *
     * @mbggenerated Thu Sep 13 18:01:17 CST 2018
     */
    private Integer countRateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income_class.server_id
     *
     * @mbggenerated Thu Sep 13 18:01:17 CST 2018
     */
    private Integer serverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income_class.channel_id
     *
     * @mbggenerated Thu Sep 13 18:01:17 CST 2018
     */
    private Integer channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income_class.recorde_time
     *
     * @mbggenerated Thu Sep 13 18:01:17 CST 2018
     */
    private Date recordeTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income_class.in_id
     *
     * @return the value of t_income_class.in_id
     *
     * @mbggenerated Thu Sep 13 18:01:17 CST 2018
     */
    public Integer getInId() {
        return inId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income_class.in_id
     *
     * @param inId the value for t_income_class.in_id
     *
     * @mbggenerated Thu Sep 13 18:01:17 CST 2018
     */
    public void setInId(Integer inId) {
        this.inId = inId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income_class.pay_ap
     *
     * @return the value of t_income_class.pay_ap
     *
     * @mbggenerated Thu Sep 13 18:01:17 CST 2018
     */
    public Double getPayAp() {
        return payAp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income_class.pay_ap
     *
     * @param payAp the value for t_income_class.pay_ap
     *
     * @mbggenerated Thu Sep 13 18:01:17 CST 2018
     */
    public void setPayAp(Double payAp) {
        this.payAp = payAp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income_class.add_ap
     *
     * @return the value of t_income_class.add_ap
     *
     * @mbggenerated Thu Sep 13 18:01:17 CST 2018
     */
    public Double getAddAp() {
        return addAp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income_class.add_ap
     *
     * @param addAp the value for t_income_class.add_ap
     *
     * @mbggenerated Thu Sep 13 18:01:17 CST 2018
     */
    public void setAddAp(Double addAp) {
        this.addAp = addAp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income_class.day_income
     *
     * @return the value of t_income_class.day_income
     *
     * @mbggenerated Thu Sep 13 18:01:17 CST 2018
     */
    public Integer getDayIncome() {
        return dayIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income_class.day_income
     *
     * @param dayIncome the value for t_income_class.day_income
     *
     * @mbggenerated Thu Sep 13 18:01:17 CST 2018
     */
    public void setDayIncome(Integer dayIncome) {
        this.dayIncome = dayIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income_class.day_payrate
     *
     * @return the value of t_income_class.day_payrate
     *
     * @mbggenerated Thu Sep 13 18:01:17 CST 2018
     */
    public String getDayPayrate() {
        return dayPayrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income_class.day_payrate
     *
     * @param dayPayrate the value for t_income_class.day_payrate
     *
     * @mbggenerated Thu Sep 13 18:01:17 CST 2018
     */
    public void setDayPayrate(String dayPayrate) {
        this.dayPayrate = dayPayrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income_class.add_rate_user
     *
     * @return the value of t_income_class.add_rate_user
     *
     * @mbggenerated Thu Sep 13 18:01:17 CST 2018
     */
    public Integer getAddRateUser() {
        return addRateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income_class.add_rate_user
     *
     * @param addRateUser the value for t_income_class.add_rate_user
     *
     * @mbggenerated Thu Sep 13 18:01:17 CST 2018
     */
    public void setAddRateUser(Integer addRateUser) {
        this.addRateUser = addRateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income_class.count_rate_user
     *
     * @return the value of t_income_class.count_rate_user
     *
     * @mbggenerated Thu Sep 13 18:01:17 CST 2018
     */
    public Integer getCountRateUser() {
        return countRateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income_class.count_rate_user
     *
     * @param countRateUser the value for t_income_class.count_rate_user
     *
     * @mbggenerated Thu Sep 13 18:01:17 CST 2018
     */
    public void setCountRateUser(Integer countRateUser) {
        this.countRateUser = countRateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income_class.server_id
     *
     * @return the value of t_income_class.server_id
     *
     * @mbggenerated Thu Sep 13 18:01:17 CST 2018
     */
    public Integer getServerId() {
        return serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income_class.server_id
     *
     * @param serverId the value for t_income_class.server_id
     *
     * @mbggenerated Thu Sep 13 18:01:17 CST 2018
     */
    public void setServerId(Integer serverId) {
        this.serverId = serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income_class.channel_id
     *
     * @return the value of t_income_class.channel_id
     *
     * @mbggenerated Thu Sep 13 18:01:17 CST 2018
     */
    public Integer getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income_class.channel_id
     *
     * @param channelId the value for t_income_class.channel_id
     *
     * @mbggenerated Thu Sep 13 18:01:17 CST 2018
     */
    public void setChannelId(Integer channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income_class.recorde_time
     *
     * @return the value of t_income_class.recorde_time
     *
     * @mbggenerated Thu Sep 13 18:01:17 CST 2018
     */
    public Date getRecordeTime() {
        return recordeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income_class.recorde_time
     *
     * @param recordeTime the value for t_income_class.recorde_time
     *
     * @mbggenerated Thu Sep 13 18:01:17 CST 2018
     */
    public void setRecordeTime(Date recordeTime) {
        this.recordeTime = recordeTime;
    }

    @Override
    public String toString() {
        return "IncomeClass{" +
                "inId=" + inId +
                ", payAp=" + payAp +
                ", addAp=" + addAp +
                ", dayIncome=" + dayIncome +
                ", dayPayrate='" + dayPayrate + '\'' +
                ", addRateUser=" + addRateUser +
                ", countRateUser=" + countRateUser +
                ", serverId=" + serverId +
                ", channelId=" + channelId +
                ", recordeTime=" + recordeTime +
                '}';
    }


}