package com.chenyou.pojo;

import java.util.Date;

public class IntimacyRank {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_intimacy_rank.tintimacy_id
     *
     * @mbggenerated Fri Sep 21 15:32:22 CST 2018
     */
    private Integer tintimacyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_intimacy_rank.intimate_rank
     *
     * @mbggenerated Fri Sep 21 15:32:22 CST 2018
     */
    private Integer intimateRank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_intimacy_rank.player_name
     *
     * @mbggenerated Fri Sep 21 15:32:22 CST 2018
     */
    private String playerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_intimacy_rank.fous_value
     *
     * @mbggenerated Fri Sep 21 15:32:22 CST 2018
     */
    private Integer fousValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_intimacy_rank.server_id
     *
     * @mbggenerated Fri Sep 21 15:32:22 CST 2018
     */
    private Integer serverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_intimacy_rank.server_name
     *
     * @mbggenerated Fri Sep 21 15:32:22 CST 2018
     */
    private String serverName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_intimacy_rank.channel_id
     *
     * @mbggenerated Fri Sep 21 15:32:22 CST 2018
     */
    private Integer channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_intimacy_rank.show_time
     *
     * @mbggenerated Fri Sep 21 15:32:22 CST 2018
     */
    private Date showTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_intimacy_rank.tintimacy_id
     *
     * @return the value of t_intimacy_rank.tintimacy_id
     *
     * @mbggenerated Fri Sep 21 15:32:22 CST 2018
     */
    public Integer getTintimacyId() {
        return tintimacyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_intimacy_rank.tintimacy_id
     *
     * @param tintimacyId the value for t_intimacy_rank.tintimacy_id
     *
     * @mbggenerated Fri Sep 21 15:32:22 CST 2018
     */
    public void setTintimacyId(Integer tintimacyId) {
        this.tintimacyId = tintimacyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_intimacy_rank.intimate_rank
     *
     * @return the value of t_intimacy_rank.intimate_rank
     *
     * @mbggenerated Fri Sep 21 15:32:22 CST 2018
     */
    public Integer getIntimateRank() {
        return intimateRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_intimacy_rank.intimate_rank
     *
     * @param intimateRank the value for t_intimacy_rank.intimate_rank
     *
     * @mbggenerated Fri Sep 21 15:32:22 CST 2018
     */
    public void setIntimateRank(Integer intimateRank) {
        this.intimateRank = intimateRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_intimacy_rank.player_name
     *
     * @return the value of t_intimacy_rank.player_name
     *
     * @mbggenerated Fri Sep 21 15:32:22 CST 2018
     */
    public String getPlayerName() {
        return playerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_intimacy_rank.player_name
     *
     * @param playerName the value for t_intimacy_rank.player_name
     *
     * @mbggenerated Fri Sep 21 15:32:22 CST 2018
     */
    public void setPlayerName(String playerName) {
        this.playerName = playerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_intimacy_rank.fous_value
     *
     * @return the value of t_intimacy_rank.fous_value
     *
     * @mbggenerated Fri Sep 21 15:32:22 CST 2018
     */
    public Integer getFousValue() {
        return fousValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_intimacy_rank.fous_value
     *
     * @param fousValue the value for t_intimacy_rank.fous_value
     *
     * @mbggenerated Fri Sep 21 15:32:22 CST 2018
     */
    public void setFousValue(Integer fousValue) {
        this.fousValue = fousValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_intimacy_rank.server_id
     *
     * @return the value of t_intimacy_rank.server_id
     *
     * @mbggenerated Fri Sep 21 15:32:22 CST 2018
     */
    public Integer getServerId() {
        return serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_intimacy_rank.server_id
     *
     * @param serverId the value for t_intimacy_rank.server_id
     *
     * @mbggenerated Fri Sep 21 15:32:22 CST 2018
     */
    public void setServerId(Integer serverId) {
        this.serverId = serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_intimacy_rank.server_name
     *
     * @return the value of t_intimacy_rank.server_name
     *
     * @mbggenerated Fri Sep 21 15:32:22 CST 2018
     */
    public String getServerName() {
        return serverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_intimacy_rank.server_name
     *
     * @param serverName the value for t_intimacy_rank.server_name
     *
     * @mbggenerated Fri Sep 21 15:32:22 CST 2018
     */
    public void setServerName(String serverName) {
        this.serverName = serverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_intimacy_rank.channel_id
     *
     * @return the value of t_intimacy_rank.channel_id
     *
     * @mbggenerated Fri Sep 21 15:32:22 CST 2018
     */
    public Integer getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_intimacy_rank.channel_id
     *
     * @param channelId the value for t_intimacy_rank.channel_id
     *
     * @mbggenerated Fri Sep 21 15:32:22 CST 2018
     */
    public void setChannelId(Integer channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_intimacy_rank.show_time
     *
     * @return the value of t_intimacy_rank.show_time
     *
     * @mbggenerated Fri Sep 21 15:32:22 CST 2018
     */
    public Date getShowTime() {
        return showTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_intimacy_rank.show_time
     *
     * @param showTime the value for t_intimacy_rank.show_time
     *
     * @mbggenerated Fri Sep 21 15:32:22 CST 2018
     */
    public void setShowTime(Date showTime) {
        this.showTime = showTime;
    }

    @Override
    public String toString() {
        return "IntimacyRank{" +
                "tintimacyId=" + tintimacyId +
                ", intimateRank=" + intimateRank +
                ", playerName='" + playerName + '\'' +
                ", fousValue=" + fousValue +
                ", serverId=" + serverId +
                ", serverName='" + serverName + '\'' +
                ", channelId=" + channelId +
                ", showTime=" + showTime +
                '}';
    }
}