package com.chenyou.pojo;

public class LevelRank {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_level_rank.level_id
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    private Integer levelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_level_rank.level_rank
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    private Integer levelRank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_level_rank.player_name
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    private String playerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_level_rank.force_value
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    private Integer forceValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_level_rank.server_id
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    private Integer serverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_level_rank.server_name
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    private String serverName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_level_rank.channel_id
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    private Integer channelId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_level_rank.level_id
     *
     * @return the value of t_level_rank.level_id
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    public Integer getLevelId() {
        return levelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_level_rank.level_id
     *
     * @param levelId the value for t_level_rank.level_id
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    public void setLevelId(Integer levelId) {
        this.levelId = levelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_level_rank.level_rank
     *
     * @return the value of t_level_rank.level_rank
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    public Integer getLevelRank() {
        return levelRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_level_rank.level_rank
     *
     * @param levelRank the value for t_level_rank.level_rank
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    public void setLevelRank(Integer levelRank) {
        this.levelRank = levelRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_level_rank.player_name
     *
     * @return the value of t_level_rank.player_name
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    public String getPlayerName() {
        return playerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_level_rank.player_name
     *
     * @param playerName the value for t_level_rank.player_name
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    public void setPlayerName(String playerName) {
        this.playerName = playerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_level_rank.force_value
     *
     * @return the value of t_level_rank.force_value
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    public Integer getForceValue() {
        return forceValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_level_rank.force_value
     *
     * @param forceValue the value for t_level_rank.force_value
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    public void setForceValue(Integer forceValue) {
        this.forceValue = forceValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_level_rank.server_id
     *
     * @return the value of t_level_rank.server_id
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    public Integer getServerId() {
        return serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_level_rank.server_id
     *
     * @param serverId the value for t_level_rank.server_id
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    public void setServerId(Integer serverId) {
        this.serverId = serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_level_rank.server_name
     *
     * @return the value of t_level_rank.server_name
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    public String getServerName() {
        return serverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_level_rank.server_name
     *
     * @param serverName the value for t_level_rank.server_name
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    public void setServerName(String serverName) {
        this.serverName = serverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_level_rank.channel_id
     *
     * @return the value of t_level_rank.channel_id
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    public Integer getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_level_rank.channel_id
     *
     * @param channelId the value for t_level_rank.channel_id
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    public void setChannelId(Integer channelId) {
        this.channelId = channelId;
    }

    @Override
    public String toString() {
        return "LevelRank{" +
                "levelId=" + levelId +
                ", levelRank=" + levelRank +
                ", playerName='" + playerName + '\'' +
                ", forceValue=" + forceValue +
                ", serverId=" + serverId +
                ", serverName='" + serverName + '\'' +
                ", channelId=" + channelId +
                '}';
    }
}