package com.chenyou.pojo;

public class LevelRank {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_level_rank.uid
     *
     * @mbggenerated Wed Oct 10 11:24:23 CST 2018
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_level_rank.level_rank
     *
     * @mbggenerated Wed Oct 10 11:24:23 CST 2018
     */
    private Integer levelRank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_level_rank.player_name
     *
     * @mbggenerated Wed Oct 10 11:24:23 CST 2018
     */
    private String playerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_level_rank.level_value
     *
     * @mbggenerated Wed Oct 10 11:24:23 CST 2018
     */
    private Integer levelValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_level_rank.server_id
     *
     * @mbggenerated Wed Oct 10 11:24:23 CST 2018
     */
    private Integer serverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_level_rank.channel_id
     *
     * @mbggenerated Wed Oct 10 11:24:23 CST 2018
     */
    private String channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_level_rank.show_time
     *
     * @mbggenerated Wed Oct 10 11:24:23 CST 2018
     */
    private String showTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_level_rank.uid
     *
     * @return the value of t_level_rank.uid
     *
     * @mbggenerated Wed Oct 10 11:24:23 CST 2018
     */
    private String serverName;

    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_level_rank.uid
     *
     * @param uid the value for t_level_rank.uid
     *
     * @mbggenerated Wed Oct 10 11:24:23 CST 2018
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_level_rank.level_rank
     *
     * @return the value of t_level_rank.level_rank
     *
     * @mbggenerated Wed Oct 10 11:24:23 CST 2018
     */
    public Integer getLevelRank() {
        return levelRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_level_rank.level_rank
     *
     * @param levelRank the value for t_level_rank.level_rank
     *
     * @mbggenerated Wed Oct 10 11:24:23 CST 2018
     */
    public void setLevelRank(Integer levelRank) {
        this.levelRank = levelRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_level_rank.player_name
     *
     * @return the value of t_level_rank.player_name
     *
     * @mbggenerated Wed Oct 10 11:24:23 CST 2018
     */
    public String getPlayerName() {
        return playerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_level_rank.player_name
     *
     * @param playerName the value for t_level_rank.player_name
     *
     * @mbggenerated Wed Oct 10 11:24:23 CST 2018
     */
    public void setPlayerName(String playerName) {
        this.playerName = playerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_level_rank.level_value
     *
     * @return the value of t_level_rank.level_value
     *
     * @mbggenerated Wed Oct 10 11:24:23 CST 2018
     */
    public Integer getLevelValue() {
        return levelValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_level_rank.level_value
     *
     * @param levelValue the value for t_level_rank.level_value
     *
     * @mbggenerated Wed Oct 10 11:24:23 CST 2018
     */
    public void setLevelValue(Integer levelValue) {
        this.levelValue = levelValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_level_rank.server_id
     *
     * @return the value of t_level_rank.server_id
     *
     * @mbggenerated Wed Oct 10 11:24:23 CST 2018
     */
    public Integer getServerId() {
        return serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_level_rank.server_id
     *
     * @param serverId the value for t_level_rank.server_id
     *
     * @mbggenerated Wed Oct 10 11:24:23 CST 2018
     */
    public void setServerId(Integer serverId) {
        this.serverId = serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_level_rank.channel_id
     *
     * @return the value of t_level_rank.channel_id
     *
     * @mbggenerated Wed Oct 10 11:24:23 CST 2018
     */
    public String getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_level_rank.channel_id
     *
     * @param channelId the value for t_level_rank.channel_id
     *
     * @mbggenerated Wed Oct 10 11:24:23 CST 2018
     */
    public void setChannelId(String channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_level_rank.show_time
     *
     * @return the value of t_level_rank.show_time
     *
     * @mbggenerated Wed Oct 10 11:24:23 CST 2018
     */
    public String getShowTime() {
        return showTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_level_rank.show_time
     *
     * @param showTime the value for t_level_rank.show_time
     *
     * @mbggenerated Wed Oct 10 11:24:23 CST 2018
     */
    public void setShowTime(String showTime) {
        this.showTime = showTime;
    }

    public String getServerName() {
        return serverName;
    }

    public void setServerName(String serverName) {
        this.serverName = serverName;
    }

    @Override
    public String toString() {
        return "LevelRank{" +
                "uid=" + uid +
                ", levelRank=" + levelRank +
                ", playerName='" + playerName + '\'' +
                ", levelValue=" + levelValue +
                ", serverId=" + serverId +
                ", channelId='" + channelId + '\'' +
                ", showTime='" + showTime + '\'' +
                ", serverName='" + serverName + '\'' +
                '}';
    }
}