package com.chenyou.pojo;

import java.util.Date;

public class LtvCount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ltv_count.ltv_id
     *
     * @mbggenerated Thu Sep 13 20:42:48 CST 2018
     */
    private Integer ltvId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ltv_count.recorde_time
     *
     * @mbggenerated Thu Sep 13 20:42:48 CST 2018
     */
    private Date recordeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ltv_count.oneday_ltv
     *
     * @mbggenerated Thu Sep 13 20:42:48 CST 2018
     */
    private Integer onedayLtv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ltv_count.twoday_ltv
     *
     * @mbggenerated Thu Sep 13 20:42:48 CST 2018
     */
    private Integer twodayLtv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ltv_count.threeday_ltv
     *
     * @mbggenerated Thu Sep 13 20:42:48 CST 2018
     */
    private Integer threedayLtv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ltv_count.fourday_ltv
     *
     * @mbggenerated Thu Sep 13 20:42:48 CST 2018
     */
    private Integer fourdayLtv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ltv_count.fiveday_ltv
     *
     * @mbggenerated Thu Sep 13 20:42:48 CST 2018
     */
    private Integer fivedayLtv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ltv_count.sixday_ltv
     *
     * @mbggenerated Thu Sep 13 20:42:48 CST 2018
     */
    private Integer sixdayLtv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ltv_count.sevenday_ltv
     *
     * @mbggenerated Thu Sep 13 20:42:48 CST 2018
     */
    private Integer sevendayLtv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ltv_count.fifteenday_ltv
     *
     * @mbggenerated Thu Sep 13 20:42:48 CST 2018
     */
    private Integer fifteendayLtv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ltv_count.thirtyday_ltv
     *
     * @mbggenerated Thu Sep 13 20:42:48 CST 2018
     */
    private Integer thirtydayLtv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ltv_count.server_id
     *
     * @mbggenerated Thu Sep 13 20:42:48 CST 2018
     */
    private Integer serverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ltv_count.channel_id
     *
     * @mbggenerated Thu Sep 13 20:42:48 CST 2018
     */
    private Integer channelId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ltv_count.ltv_id
     *
     * @return the value of t_ltv_count.ltv_id
     *
     * @mbggenerated Thu Sep 13 20:42:48 CST 2018
     */
    public Integer getLtvId() {
        return ltvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ltv_count.ltv_id
     *
     * @param ltvId the value for t_ltv_count.ltv_id
     *
     * @mbggenerated Thu Sep 13 20:42:48 CST 2018
     */
    public void setLtvId(Integer ltvId) {
        this.ltvId = ltvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ltv_count.recorde_time
     *
     * @return the value of t_ltv_count.recorde_time
     *
     * @mbggenerated Thu Sep 13 20:42:48 CST 2018
     */
    public Date getRecordeTime() {
        return recordeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ltv_count.recorde_time
     *
     * @param recordeTime the value for t_ltv_count.recorde_time
     *
     * @mbggenerated Thu Sep 13 20:42:48 CST 2018
     */
    public void setRecordeTime(Date recordeTime) {
        this.recordeTime = recordeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ltv_count.oneday_ltv
     *
     * @return the value of t_ltv_count.oneday_ltv
     *
     * @mbggenerated Thu Sep 13 20:42:48 CST 2018
     */
    public Integer getOnedayLtv() {
        return onedayLtv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ltv_count.oneday_ltv
     *
     * @param onedayLtv the value for t_ltv_count.oneday_ltv
     *
     * @mbggenerated Thu Sep 13 20:42:48 CST 2018
     */
    public void setOnedayLtv(Integer onedayLtv) {
        this.onedayLtv = onedayLtv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ltv_count.twoday_ltv
     *
     * @return the value of t_ltv_count.twoday_ltv
     *
     * @mbggenerated Thu Sep 13 20:42:48 CST 2018
     */
    public Integer getTwodayLtv() {
        return twodayLtv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ltv_count.twoday_ltv
     *
     * @param twodayLtv the value for t_ltv_count.twoday_ltv
     *
     * @mbggenerated Thu Sep 13 20:42:48 CST 2018
     */
    public void setTwodayLtv(Integer twodayLtv) {
        this.twodayLtv = twodayLtv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ltv_count.threeday_ltv
     *
     * @return the value of t_ltv_count.threeday_ltv
     *
     * @mbggenerated Thu Sep 13 20:42:48 CST 2018
     */
    public Integer getThreedayLtv() {
        return threedayLtv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ltv_count.threeday_ltv
     *
     * @param threedayLtv the value for t_ltv_count.threeday_ltv
     *
     * @mbggenerated Thu Sep 13 20:42:48 CST 2018
     */
    public void setThreedayLtv(Integer threedayLtv) {
        this.threedayLtv = threedayLtv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ltv_count.fourday_ltv
     *
     * @return the value of t_ltv_count.fourday_ltv
     *
     * @mbggenerated Thu Sep 13 20:42:48 CST 2018
     */
    public Integer getFourdayLtv() {
        return fourdayLtv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ltv_count.fourday_ltv
     *
     * @param fourdayLtv the value for t_ltv_count.fourday_ltv
     *
     * @mbggenerated Thu Sep 13 20:42:48 CST 2018
     */
    public void setFourdayLtv(Integer fourdayLtv) {
        this.fourdayLtv = fourdayLtv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ltv_count.fiveday_ltv
     *
     * @return the value of t_ltv_count.fiveday_ltv
     *
     * @mbggenerated Thu Sep 13 20:42:48 CST 2018
     */
    public Integer getFivedayLtv() {
        return fivedayLtv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ltv_count.fiveday_ltv
     *
     * @param fivedayLtv the value for t_ltv_count.fiveday_ltv
     *
     * @mbggenerated Thu Sep 13 20:42:48 CST 2018
     */
    public void setFivedayLtv(Integer fivedayLtv) {
        this.fivedayLtv = fivedayLtv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ltv_count.sixday_ltv
     *
     * @return the value of t_ltv_count.sixday_ltv
     *
     * @mbggenerated Thu Sep 13 20:42:48 CST 2018
     */
    public Integer getSixdayLtv() {
        return sixdayLtv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ltv_count.sixday_ltv
     *
     * @param sixdayLtv the value for t_ltv_count.sixday_ltv
     *
     * @mbggenerated Thu Sep 13 20:42:48 CST 2018
     */
    public void setSixdayLtv(Integer sixdayLtv) {
        this.sixdayLtv = sixdayLtv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ltv_count.sevenday_ltv
     *
     * @return the value of t_ltv_count.sevenday_ltv
     *
     * @mbggenerated Thu Sep 13 20:42:48 CST 2018
     */
    public Integer getSevendayLtv() {
        return sevendayLtv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ltv_count.sevenday_ltv
     *
     * @param sevendayLtv the value for t_ltv_count.sevenday_ltv
     *
     * @mbggenerated Thu Sep 13 20:42:48 CST 2018
     */
    public void setSevendayLtv(Integer sevendayLtv) {
        this.sevendayLtv = sevendayLtv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ltv_count.fifteenday_ltv
     *
     * @return the value of t_ltv_count.fifteenday_ltv
     *
     * @mbggenerated Thu Sep 13 20:42:48 CST 2018
     */
    public Integer getFifteendayLtv() {
        return fifteendayLtv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ltv_count.fifteenday_ltv
     *
     * @param fifteendayLtv the value for t_ltv_count.fifteenday_ltv
     *
     * @mbggenerated Thu Sep 13 20:42:48 CST 2018
     */
    public void setFifteendayLtv(Integer fifteendayLtv) {
        this.fifteendayLtv = fifteendayLtv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ltv_count.thirtyday_ltv
     *
     * @return the value of t_ltv_count.thirtyday_ltv
     *
     * @mbggenerated Thu Sep 13 20:42:48 CST 2018
     */
    public Integer getThirtydayLtv() {
        return thirtydayLtv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ltv_count.thirtyday_ltv
     *
     * @param thirtydayLtv the value for t_ltv_count.thirtyday_ltv
     *
     * @mbggenerated Thu Sep 13 20:42:48 CST 2018
     */
    public void setThirtydayLtv(Integer thirtydayLtv) {
        this.thirtydayLtv = thirtydayLtv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ltv_count.server_id
     *
     * @return the value of t_ltv_count.server_id
     *
     * @mbggenerated Thu Sep 13 20:42:48 CST 2018
     */
    public Integer getServerId() {
        return serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ltv_count.server_id
     *
     * @param serverId the value for t_ltv_count.server_id
     *
     * @mbggenerated Thu Sep 13 20:42:48 CST 2018
     */
    public void setServerId(Integer serverId) {
        this.serverId = serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ltv_count.channel_id
     *
     * @return the value of t_ltv_count.channel_id
     *
     * @mbggenerated Thu Sep 13 20:42:48 CST 2018
     */
    public Integer getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ltv_count.channel_id
     *
     * @param channelId the value for t_ltv_count.channel_id
     *
     * @mbggenerated Thu Sep 13 20:42:48 CST 2018
     */
    public void setChannelId(Integer channelId) {
        this.channelId = channelId;
    }


    @Override
    public String toString() {
        return "LtvCount{" +
                "ltvId=" + ltvId +
                ", recordeTime=" + recordeTime +
                ", onedayLtv=" + onedayLtv +
                ", twodayLtv=" + twodayLtv +
                ", threedayLtv=" + threedayLtv +
                ", fourdayLtv=" + fourdayLtv +
                ", fivedayLtv=" + fivedayLtv +
                ", sixdayLtv=" + sixdayLtv +
                ", sevendayLtv=" + sevendayLtv +
                ", fifteendayLtv=" + fifteendayLtv +
                ", thirtydayLtv=" + thirtydayLtv +
                ", serverId=" + serverId +
                ", channelId=" + channelId +
                '}';
    }
}