package com.chenyou.pojo;

public class PointAnalyse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_point_analyse.charging_id
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    private Integer chargingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_point_analyse.charging_time
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    private String chargingTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_point_analyse.buy_num_user
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    private Integer buyNumUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_point_analyse.recharge_first_buyuser
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    private Integer rechargeFirstBuyuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_point_analyse.server_id
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    private Integer serverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_point_analyse.channel_id
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    private Integer channelId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_point_analyse.charging_id
     *
     * @return the value of t_point_analyse.charging_id
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    public Integer getChargingId() {
        return chargingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_point_analyse.charging_id
     *
     * @param chargingId the value for t_point_analyse.charging_id
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    public void setChargingId(Integer chargingId) {
        this.chargingId = chargingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_point_analyse.charging_time
     *
     * @return the value of t_point_analyse.charging_time
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    public String getChargingTime() {
        return chargingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_point_analyse.charging_time
     *
     * @param chargingTime the value for t_point_analyse.charging_time
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    public void setChargingTime(String chargingTime) {
        this.chargingTime = chargingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_point_analyse.buy_num_user
     *
     * @return the value of t_point_analyse.buy_num_user
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    public Integer getBuyNumUser() {
        return buyNumUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_point_analyse.buy_num_user
     *
     * @param buyNumUser the value for t_point_analyse.buy_num_user
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    public void setBuyNumUser(Integer buyNumUser) {
        this.buyNumUser = buyNumUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_point_analyse.recharge_first_buyuser
     *
     * @return the value of t_point_analyse.recharge_first_buyuser
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    public Integer getRechargeFirstBuyuser() {
        return rechargeFirstBuyuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_point_analyse.recharge_first_buyuser
     *
     * @param rechargeFirstBuyuser the value for t_point_analyse.recharge_first_buyuser
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    public void setRechargeFirstBuyuser(Integer rechargeFirstBuyuser) {
        this.rechargeFirstBuyuser = rechargeFirstBuyuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_point_analyse.server_id
     *
     * @return the value of t_point_analyse.server_id
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    public Integer getServerId() {
        return serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_point_analyse.server_id
     *
     * @param serverId the value for t_point_analyse.server_id
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    public void setServerId(Integer serverId) {
        this.serverId = serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_point_analyse.channel_id
     *
     * @return the value of t_point_analyse.channel_id
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    public Integer getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_point_analyse.channel_id
     *
     * @param channelId the value for t_point_analyse.channel_id
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    public void setChannelId(Integer channelId) {
        this.channelId = channelId;
    }

    @Override
    public String toString() {
        return "PointAnalyse{" +
                "chargingId=" + chargingId +
                ", chargingTime='" + chargingTime + '\'' +
                ", buyNumUser=" + buyNumUser +
                ", rechargeFirstBuyuser=" + rechargeFirstBuyuser +
                ", serverId=" + serverId +
                ", channelId=" + channelId +
                '}';
    }
}