package com.chenyou.pojo;

public class RetainPlayer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_retain_player.retain_id
     *
     * @mbggenerated Wed Oct 10 09:43:33 CST 2018
     */
    private Integer retainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_retain_player.show_time
     *
     * @mbggenerated Wed Oct 10 09:43:33 CST 2018
     */
    private String showTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_retain_player.oneday_retain
     *
     * @mbggenerated Wed Oct 10 09:43:33 CST 2018
     */
    private String onedayRetain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_retain_player.threeday_retain
     *
     * @mbggenerated Wed Oct 10 09:43:33 CST 2018
     */
    private String threedayRetain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_retain_player.weekly_retain
     *
     * @mbggenerated Wed Oct 10 09:43:33 CST 2018
     */
    private String weeklyRetain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_retain_player.server_id
     *
     * @mbggenerated Wed Oct 10 09:43:33 CST 2018
     */
    private Integer serverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_retain_player.channel_id
     *
     * @mbggenerated Wed Oct 10 09:43:33 CST 2018
     */
    private String channelId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_retain_player.retain_id
     *
     * @return the value of t_retain_player.retain_id
     *
     * @mbggenerated Wed Oct 10 09:43:33 CST 2018
     */
    public Integer getRetainId() {
        return retainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_retain_player.retain_id
     *
     * @param retainId the value for t_retain_player.retain_id
     *
     * @mbggenerated Wed Oct 10 09:43:33 CST 2018
     */
    public void setRetainId(Integer retainId) {
        this.retainId = retainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_retain_player.show_time
     *
     * @return the value of t_retain_player.show_time
     *
     * @mbggenerated Wed Oct 10 09:43:33 CST 2018
     */
    public String getShowTime() {
        return showTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_retain_player.show_time
     *
     * @param showTime the value for t_retain_player.show_time
     *
     * @mbggenerated Wed Oct 10 09:43:33 CST 2018
     */
    public void setShowTime(String showTime) {
        this.showTime = showTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_retain_player.oneday_retain
     *
     * @return the value of t_retain_player.oneday_retain
     *
     * @mbggenerated Wed Oct 10 09:43:33 CST 2018
     */
    public String getOnedayRetain() {
        return onedayRetain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_retain_player.oneday_retain
     *
     * @param onedayRetain the value for t_retain_player.oneday_retain
     *
     * @mbggenerated Wed Oct 10 09:43:33 CST 2018
     */
    public void setOnedayRetain(String onedayRetain) {
        this.onedayRetain = onedayRetain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_retain_player.threeday_retain
     *
     * @return the value of t_retain_player.threeday_retain
     *
     * @mbggenerated Wed Oct 10 09:43:33 CST 2018
     */
    public String getThreedayRetain() {
        return threedayRetain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_retain_player.threeday_retain
     *
     * @param threedayRetain the value for t_retain_player.threeday_retain
     *
     * @mbggenerated Wed Oct 10 09:43:33 CST 2018
     */
    public void setThreedayRetain(String threedayRetain) {
        this.threedayRetain = threedayRetain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_retain_player.weekly_retain
     *
     * @return the value of t_retain_player.weekly_retain
     *
     * @mbggenerated Wed Oct 10 09:43:33 CST 2018
     */
    public String getWeeklyRetain() {
        return weeklyRetain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_retain_player.weekly_retain
     *
     * @param weeklyRetain the value for t_retain_player.weekly_retain
     *
     * @mbggenerated Wed Oct 10 09:43:33 CST 2018
     */
    public void setWeeklyRetain(String weeklyRetain) {
        this.weeklyRetain = weeklyRetain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_retain_player.server_id
     *
     * @return the value of t_retain_player.server_id
     *
     * @mbggenerated Wed Oct 10 09:43:33 CST 2018
     */
    public Integer getServerId() {
        return serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_retain_player.server_id
     *
     * @param serverId the value for t_retain_player.server_id
     *
     * @mbggenerated Wed Oct 10 09:43:33 CST 2018
     */
    public void setServerId(Integer serverId) {
        this.serverId = serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_retain_player.channel_id
     *
     * @return the value of t_retain_player.channel_id
     *
     * @mbggenerated Wed Oct 10 09:43:33 CST 2018
     */
    public String getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_retain_player.channel_id
     *
     * @param channelId the value for t_retain_player.channel_id
     *
     * @mbggenerated Wed Oct 10 09:43:33 CST 2018
     */
    public void setChannelId(String channelId) {
        this.channelId = channelId;
    }

    @Override
    public String toString() {
        return "RetainPlayer{" +
                "retainId=" + retainId +
                ", showTime='" + showTime + '\'' +
                ", onedayRetain='" + onedayRetain + '\'' +
                ", threedayRetain='" + threedayRetain + '\'' +
                ", weeklyRetain='" + weeklyRetain + '\'' +
                ", serverId=" + serverId +
                ", channelId='" + channelId + '\'' +
                '}';
    }
}