package com.chenyou.pojo;

import java.util.ArrayList;
import java.util.List;

public class TaskMessageExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_task_message
     *
     * @mbggenerated Fri Sep 14 17:06:49 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_task_message
     *
     * @mbggenerated Fri Sep 14 17:06:49 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_task_message
     *
     * @mbggenerated Fri Sep 14 17:06:49 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_message
     *
     * @mbggenerated Fri Sep 14 17:06:49 CST 2018
     */
    public TaskMessageExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_message
     *
     * @mbggenerated Fri Sep 14 17:06:49 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_message
     *
     * @mbggenerated Fri Sep 14 17:06:49 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_message
     *
     * @mbggenerated Fri Sep 14 17:06:49 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_message
     *
     * @mbggenerated Fri Sep 14 17:06:49 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_message
     *
     * @mbggenerated Fri Sep 14 17:06:49 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_message
     *
     * @mbggenerated Fri Sep 14 17:06:49 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_message
     *
     * @mbggenerated Fri Sep 14 17:06:49 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_message
     *
     * @mbggenerated Fri Sep 14 17:06:49 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_message
     *
     * @mbggenerated Fri Sep 14 17:06:49 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_message
     *
     * @mbggenerated Fri Sep 14 17:06:49 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_task_message
     *
     * @mbggenerated Fri Sep 14 17:06:49 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTaskIdIsNull() {
            addCriterion("task_id is null");
            return (Criteria) this;
        }

        public Criteria andTaskIdIsNotNull() {
            addCriterion("task_id is not null");
            return (Criteria) this;
        }

        public Criteria andTaskIdEqualTo(Integer value) {
            addCriterion("task_id =", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotEqualTo(Integer value) {
            addCriterion("task_id <>", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThan(Integer value) {
            addCriterion("task_id >", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("task_id >=", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThan(Integer value) {
            addCriterion("task_id <", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThanOrEqualTo(Integer value) {
            addCriterion("task_id <=", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdIn(List<Integer> values) {
            addCriterion("task_id in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotIn(List<Integer> values) {
            addCriterion("task_id not in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdBetween(Integer value1, Integer value2) {
            addCriterion("task_id between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotBetween(Integer value1, Integer value2) {
            addCriterion("task_id not between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskListIsNull() {
            addCriterion("task_list is null");
            return (Criteria) this;
        }

        public Criteria andTaskListIsNotNull() {
            addCriterion("task_list is not null");
            return (Criteria) this;
        }

        public Criteria andTaskListEqualTo(String value) {
            addCriterion("task_list =", value, "taskList");
            return (Criteria) this;
        }

        public Criteria andTaskListNotEqualTo(String value) {
            addCriterion("task_list <>", value, "taskList");
            return (Criteria) this;
        }

        public Criteria andTaskListGreaterThan(String value) {
            addCriterion("task_list >", value, "taskList");
            return (Criteria) this;
        }

        public Criteria andTaskListGreaterThanOrEqualTo(String value) {
            addCriterion("task_list >=", value, "taskList");
            return (Criteria) this;
        }

        public Criteria andTaskListLessThan(String value) {
            addCriterion("task_list <", value, "taskList");
            return (Criteria) this;
        }

        public Criteria andTaskListLessThanOrEqualTo(String value) {
            addCriterion("task_list <=", value, "taskList");
            return (Criteria) this;
        }

        public Criteria andTaskListLike(String value) {
            addCriterion("task_list like", value, "taskList");
            return (Criteria) this;
        }

        public Criteria andTaskListNotLike(String value) {
            addCriterion("task_list not like", value, "taskList");
            return (Criteria) this;
        }

        public Criteria andTaskListIn(List<String> values) {
            addCriterion("task_list in", values, "taskList");
            return (Criteria) this;
        }

        public Criteria andTaskListNotIn(List<String> values) {
            addCriterion("task_list not in", values, "taskList");
            return (Criteria) this;
        }

        public Criteria andTaskListBetween(String value1, String value2) {
            addCriterion("task_list between", value1, value2, "taskList");
            return (Criteria) this;
        }

        public Criteria andTaskListNotBetween(String value1, String value2) {
            addCriterion("task_list not between", value1, value2, "taskList");
            return (Criteria) this;
        }

        public Criteria andNowProgressNumIsNull() {
            addCriterion("now_progress_num is null");
            return (Criteria) this;
        }

        public Criteria andNowProgressNumIsNotNull() {
            addCriterion("now_progress_num is not null");
            return (Criteria) this;
        }

        public Criteria andNowProgressNumEqualTo(Integer value) {
            addCriterion("now_progress_num =", value, "nowProgressNum");
            return (Criteria) this;
        }

        public Criteria andNowProgressNumNotEqualTo(Integer value) {
            addCriterion("now_progress_num <>", value, "nowProgressNum");
            return (Criteria) this;
        }

        public Criteria andNowProgressNumGreaterThan(Integer value) {
            addCriterion("now_progress_num >", value, "nowProgressNum");
            return (Criteria) this;
        }

        public Criteria andNowProgressNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("now_progress_num >=", value, "nowProgressNum");
            return (Criteria) this;
        }

        public Criteria andNowProgressNumLessThan(Integer value) {
            addCriterion("now_progress_num <", value, "nowProgressNum");
            return (Criteria) this;
        }

        public Criteria andNowProgressNumLessThanOrEqualTo(Integer value) {
            addCriterion("now_progress_num <=", value, "nowProgressNum");
            return (Criteria) this;
        }

        public Criteria andNowProgressNumIn(List<Integer> values) {
            addCriterion("now_progress_num in", values, "nowProgressNum");
            return (Criteria) this;
        }

        public Criteria andNowProgressNumNotIn(List<Integer> values) {
            addCriterion("now_progress_num not in", values, "nowProgressNum");
            return (Criteria) this;
        }

        public Criteria andNowProgressNumBetween(Integer value1, Integer value2) {
            addCriterion("now_progress_num between", value1, value2, "nowProgressNum");
            return (Criteria) this;
        }

        public Criteria andNowProgressNumNotBetween(Integer value1, Integer value2) {
            addCriterion("now_progress_num not between", value1, value2, "nowProgressNum");
            return (Criteria) this;
        }

        public Criteria andServerIdIsNull() {
            addCriterion("server_id is null");
            return (Criteria) this;
        }

        public Criteria andServerIdIsNotNull() {
            addCriterion("server_id is not null");
            return (Criteria) this;
        }

        public Criteria andServerIdEqualTo(Integer value) {
            addCriterion("server_id =", value, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdNotEqualTo(Integer value) {
            addCriterion("server_id <>", value, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdGreaterThan(Integer value) {
            addCriterion("server_id >", value, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("server_id >=", value, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdLessThan(Integer value) {
            addCriterion("server_id <", value, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdLessThanOrEqualTo(Integer value) {
            addCriterion("server_id <=", value, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdIn(List<Integer> values) {
            addCriterion("server_id in", values, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdNotIn(List<Integer> values) {
            addCriterion("server_id not in", values, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdBetween(Integer value1, Integer value2) {
            addCriterion("server_id between", value1, value2, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("server_id not between", value1, value2, "serverId");
            return (Criteria) this;
        }

        public Criteria andChannelIdIsNull() {
            addCriterion("channel_id is null");
            return (Criteria) this;
        }

        public Criteria andChannelIdIsNotNull() {
            addCriterion("channel_id is not null");
            return (Criteria) this;
        }

        public Criteria andChannelIdEqualTo(Integer value) {
            addCriterion("channel_id =", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdNotEqualTo(Integer value) {
            addCriterion("channel_id <>", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdGreaterThan(Integer value) {
            addCriterion("channel_id >", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("channel_id >=", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdLessThan(Integer value) {
            addCriterion("channel_id <", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdLessThanOrEqualTo(Integer value) {
            addCriterion("channel_id <=", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdIn(List<Integer> values) {
            addCriterion("channel_id in", values, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdNotIn(List<Integer> values) {
            addCriterion("channel_id not in", values, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdBetween(Integer value1, Integer value2) {
            addCriterion("channel_id between", value1, value2, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdNotBetween(Integer value1, Integer value2) {
            addCriterion("channel_id not between", value1, value2, "channelId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_task_message
     *
     * @mbggenerated do_not_delete_during_merge Fri Sep 14 17:06:49 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_task_message
     *
     * @mbggenerated Fri Sep 14 17:06:49 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}