package com.chenyou.pojo;

public class TaskMessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_message.task_id
     *
     * @mbggenerated Wed Oct 10 11:49:41 CST 2018
     */
    private Integer taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_message.task_list
     *
     * @mbggenerated Wed Oct 10 11:49:41 CST 2018
     */
    private String taskList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_message.now_progress_num
     *
     * @mbggenerated Wed Oct 10 11:49:41 CST 2018
     */
    private Integer nowProgressNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_message.server_id
     *
     * @mbggenerated Wed Oct 10 11:49:41 CST 2018
     */
    private Integer serverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_message.channel_id
     *
     * @mbggenerated Wed Oct 10 11:49:41 CST 2018
     */
    private String channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_message.show_time
     *
     * @mbggenerated Wed Oct 10 11:49:41 CST 2018
     */
    private String showTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_message.task_id
     *
     * @return the value of t_task_message.task_id
     *
     * @mbggenerated Wed Oct 10 11:49:41 CST 2018
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_message.task_id
     *
     * @param taskId the value for t_task_message.task_id
     *
     * @mbggenerated Wed Oct 10 11:49:41 CST 2018
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_message.task_list
     *
     * @return the value of t_task_message.task_list
     *
     * @mbggenerated Wed Oct 10 11:49:41 CST 2018
     */
    public String getTaskList() {
        return taskList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_message.task_list
     *
     * @param taskList the value for t_task_message.task_list
     *
     * @mbggenerated Wed Oct 10 11:49:41 CST 2018
     */
    public void setTaskList(String taskList) {
        this.taskList = taskList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_message.now_progress_num
     *
     * @return the value of t_task_message.now_progress_num
     *
     * @mbggenerated Wed Oct 10 11:49:41 CST 2018
     */
    public Integer getNowProgressNum() {
        return nowProgressNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_message.now_progress_num
     *
     * @param nowProgressNum the value for t_task_message.now_progress_num
     *
     * @mbggenerated Wed Oct 10 11:49:41 CST 2018
     */
    public void setNowProgressNum(Integer nowProgressNum) {
        this.nowProgressNum = nowProgressNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_message.server_id
     *
     * @return the value of t_task_message.server_id
     *
     * @mbggenerated Wed Oct 10 11:49:41 CST 2018
     */
    public Integer getServerId() {
        return serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_message.server_id
     *
     * @param serverId the value for t_task_message.server_id
     *
     * @mbggenerated Wed Oct 10 11:49:41 CST 2018
     */
    public void setServerId(Integer serverId) {
        this.serverId = serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_message.channel_id
     *
     * @return the value of t_task_message.channel_id
     *
     * @mbggenerated Wed Oct 10 11:49:41 CST 2018
     */
    public String getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_message.channel_id
     *
     * @param channelId the value for t_task_message.channel_id
     *
     * @mbggenerated Wed Oct 10 11:49:41 CST 2018
     */
    public void setChannelId(String channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_message.show_time
     *
     * @return the value of t_task_message.show_time
     *
     * @mbggenerated Wed Oct 10 11:49:41 CST 2018
     */
    public String getShowTime() {
        return showTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_message.show_time
     *
     * @param showTime the value for t_task_message.show_time
     *
     * @mbggenerated Wed Oct 10 11:49:41 CST 2018
     */
    public void setShowTime(String showTime) {
        this.showTime = showTime;
    }

    @Override
    public String toString() {
        return "TaskMessage{" +
                "taskId=" + taskId +
                ", taskList='" + taskList + '\'' +
                ", nowProgressNum=" + nowProgressNum +
                ", serverId=" + serverId +
                ", channelId='" + channelId + '\'' +
                ", showTime='" + showTime + '\'' +
                '}';
    }
}