package com.chenyou.pojo;

public class TemplateName {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template_name.id
     *
     * @mbggenerated Wed Nov 21 10:54:11 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template_name.template_name
     *
     * @mbggenerated Wed Nov 21 10:54:11 CST 2018
     */
    private String templateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template_name.record_time
     *
     * @mbggenerated Wed Nov 21 10:54:11 CST 2018
     */
    private String recordTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template_name.create_people
     *
     * @mbggenerated Wed Nov 21 10:54:11 CST 2018
     */
    private String createPeople;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template_name.id
     *
     * @return the value of t_template_name.id
     *
     * @mbggenerated Wed Nov 21 10:54:11 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template_name.id
     *
     * @param id the value for t_template_name.id
     *
     * @mbggenerated Wed Nov 21 10:54:11 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template_name.template_name
     *
     * @return the value of t_template_name.template_name
     *
     * @mbggenerated Wed Nov 21 10:54:11 CST 2018
     */
    public String getTemplateName() {
        return templateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template_name.template_name
     *
     * @param templateName the value for t_template_name.template_name
     *
     * @mbggenerated Wed Nov 21 10:54:11 CST 2018
     */
    public void setTemplateName(String templateName) {
        this.templateName = templateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template_name.record_time
     *
     * @return the value of t_template_name.record_time
     *
     * @mbggenerated Wed Nov 21 10:54:11 CST 2018
     */
    public String getRecordTime() {
        return recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template_name.record_time
     *
     * @param recordTime the value for t_template_name.record_time
     *
     * @mbggenerated Wed Nov 21 10:54:11 CST 2018
     */
    public void setRecordTime(String recordTime) {
        this.recordTime = recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template_name.create_people
     *
     * @return the value of t_template_name.create_people
     *
     * @mbggenerated Wed Nov 21 10:54:11 CST 2018
     */
    public String getCreatePeople() {
        return createPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template_name.create_people
     *
     * @param createPeople the value for t_template_name.create_people
     *
     * @mbggenerated Wed Nov 21 10:54:11 CST 2018
     */
    public void setCreatePeople(String createPeople) {
        this.createPeople = createPeople;
    }

    @Override
    public String toString() {
        return "TemplateName{" + "id=" + id + ", templateName='" + templateName + '\'' + ", recordTime='" + recordTime + '\'' + ", createPeople='" + createPeople + '\'' + '}';
    }
}