package com.chenyou.pojo;

public class TemplateOpen {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template_open.id
     *
     * @mbggenerated Mon Dec 03 19:52:29 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template_open.server_id
     *
     * @mbggenerated Mon Dec 03 19:52:29 CST 2018
     */
    private Integer serverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template_open.start
     *
     * @mbggenerated Mon Dec 03 19:52:29 CST 2018
     */
    private String start;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template_open.end
     *
     * @mbggenerated Mon Dec 03 19:52:29 CST 2018
     */
    private String end;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template_open.delay_days
     *
     * @mbggenerated Mon Dec 03 19:52:29 CST 2018
     */
    private Integer delayDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template_open.active_id
     *
     * @mbggenerated Mon Dec 03 19:52:29 CST 2018
     */
    private String activeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template_open.template_id
     *
     * @mbggenerated Mon Dec 03 19:52:29 CST 2018
     */
    private Integer templateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template_open.operator
     *
     * @mbggenerated Mon Dec 03 19:52:29 CST 2018
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template_open.record_time
     *
     * @mbggenerated Mon Dec 03 19:52:29 CST 2018
     */
    private String recordTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template_open.active_status
     *
     * @mbggenerated Mon Dec 03 19:52:29 CST 2018
     */
    private Integer activeStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template_open.id
     *
     * @return the value of t_template_open.id
     *
     * @mbggenerated Mon Dec 03 19:52:29 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template_open.id
     *
     * @param id the value for t_template_open.id
     *
     * @mbggenerated Mon Dec 03 19:52:29 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template_open.server_id
     *
     * @return the value of t_template_open.server_id
     *
     * @mbggenerated Mon Dec 03 19:52:29 CST 2018
     */
    public Integer getServerId() {
        return serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template_open.server_id
     *
     * @param serverId the value for t_template_open.server_id
     *
     * @mbggenerated Mon Dec 03 19:52:29 CST 2018
     */
    public void setServerId(Integer serverId) {
        this.serverId = serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template_open.start
     *
     * @return the value of t_template_open.start
     *
     * @mbggenerated Mon Dec 03 19:52:29 CST 2018
     */
    public String getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template_open.start
     *
     * @param start the value for t_template_open.start
     *
     * @mbggenerated Mon Dec 03 19:52:29 CST 2018
     */
    public void setStart(String start) {
        this.start = start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template_open.end
     *
     * @return the value of t_template_open.end
     *
     * @mbggenerated Mon Dec 03 19:52:29 CST 2018
     */
    public String getEnd() {
        return end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template_open.end
     *
     * @param end the value for t_template_open.end
     *
     * @mbggenerated Mon Dec 03 19:52:29 CST 2018
     */
    public void setEnd(String end) {
        this.end = end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template_open.delay_days
     *
     * @return the value of t_template_open.delay_days
     *
     * @mbggenerated Mon Dec 03 19:52:29 CST 2018
     */
    public Integer getDelayDays() {
        return delayDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template_open.delay_days
     *
     * @param delayDays the value for t_template_open.delay_days
     *
     * @mbggenerated Mon Dec 03 19:52:29 CST 2018
     */
    public void setDelayDays(Integer delayDays) {
        this.delayDays = delayDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template_open.active_id
     *
     * @return the value of t_template_open.active_id
     *
     * @mbggenerated Mon Dec 03 19:52:29 CST 2018
     */
    public String getActiveId() {
        return activeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template_open.active_id
     *
     * @param activeId the value for t_template_open.active_id
     *
     * @mbggenerated Mon Dec 03 19:52:29 CST 2018
     */
    public void setActiveId(String activeId) {
        this.activeId = activeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template_open.template_id
     *
     * @return the value of t_template_open.template_id
     *
     * @mbggenerated Mon Dec 03 19:52:29 CST 2018
     */
    public Integer getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template_open.template_id
     *
     * @param templateId the value for t_template_open.template_id
     *
     * @mbggenerated Mon Dec 03 19:52:29 CST 2018
     */
    public void setTemplateId(Integer templateId) {
        this.templateId = templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template_open.operator
     *
     * @return the value of t_template_open.operator
     *
     * @mbggenerated Mon Dec 03 19:52:29 CST 2018
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template_open.operator
     *
     * @param operator the value for t_template_open.operator
     *
     * @mbggenerated Mon Dec 03 19:52:29 CST 2018
     */
    public void setOperator(String operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template_open.record_time
     *
     * @return the value of t_template_open.record_time
     *
     * @mbggenerated Mon Dec 03 19:52:29 CST 2018
     */
    public String getRecordTime() {
        return recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template_open.record_time
     *
     * @param recordTime the value for t_template_open.record_time
     *
     * @mbggenerated Mon Dec 03 19:52:29 CST 2018
     */
    public void setRecordTime(String recordTime) {
        this.recordTime = recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template_open.active_status
     *
     * @return the value of t_template_open.active_status
     *
     * @mbggenerated Mon Dec 03 19:52:29 CST 2018
     */
    public Integer getActiveStatus() {
        return activeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template_open.active_status
     *
     * @param activeStatus the value for t_template_open.active_status
     *
     * @mbggenerated Mon Dec 03 19:52:29 CST 2018
     */
    public void setActiveStatus(Integer activeStatus) {
        this.activeStatus = activeStatus;
    }

    @Override
    public String toString() {
        return "TemplateOpen{" + "id=" + id + ", serverId=" + serverId + ", start='" + start + '\'' + ", end='" + end + '\'' + ", delayDays=" + delayDays + ", activeId='" + activeId + '\'' + ", templateId=" + templateId + ", operator='" + operator + '\'' + ", recordTime='" + recordTime + '\'' + ", activeStatus=" + activeStatus + '}';
    }
}