package com.chenyou.pojo;

public class TemplateManager {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template_manager.id
     *
     * @mbggenerated Mon Dec 03 17:25:14 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template_manager.template_id
     *
     * @mbggenerated Mon Dec 03 17:25:14 CST 2018
     */
    private Integer templateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template_manager.template_name
     *
     * @mbggenerated Mon Dec 03 17:25:14 CST 2018
     */
    private String templateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template_manager.active_id
     *
     * @mbggenerated Mon Dec 03 17:25:14 CST 2018
     */
    private String activeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template_manager.open_takes_day
     *
     * @mbggenerated Mon Dec 03 17:25:14 CST 2018
     */
    private Integer openTakesDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template_manager.delay_days
     *
     * @mbggenerated Mon Dec 03 17:25:14 CST 2018
     */
    private Integer delayDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template_manager.delay_status
     *
     * @mbggenerated Mon Dec 03 17:25:14 CST 2018
     */
    private Integer delayStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template_manager.record_time
     *
     * @mbggenerated Mon Dec 03 17:25:14 CST 2018
     */
    private String recordTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template_manager.sort
     *
     * @mbggenerated Mon Dec 03 17:25:14 CST 2018
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template_manager.create_people
     *
     * @mbggenerated Mon Dec 03 17:25:14 CST 2018
     */
    private String createPeople;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template_manager.remark
     *
     * @mbggenerated Mon Dec 03 17:25:14 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template_manager.id
     *
     * @return the value of t_template_manager.id
     *
     * @mbggenerated Mon Dec 03 17:25:14 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template_manager.id
     *
     * @param id the value for t_template_manager.id
     *
     * @mbggenerated Mon Dec 03 17:25:14 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template_manager.template_id
     *
     * @return the value of t_template_manager.template_id
     *
     * @mbggenerated Mon Dec 03 17:25:14 CST 2018
     */
    public Integer getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template_manager.template_id
     *
     * @param templateId the value for t_template_manager.template_id
     *
     * @mbggenerated Mon Dec 03 17:25:14 CST 2018
     */
    public void setTemplateId(Integer templateId) {
        this.templateId = templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template_manager.template_name
     *
     * @return the value of t_template_manager.template_name
     *
     * @mbggenerated Mon Dec 03 17:25:14 CST 2018
     */
    public String getTemplateName() {
        return templateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template_manager.template_name
     *
     * @param templateName the value for t_template_manager.template_name
     *
     * @mbggenerated Mon Dec 03 17:25:14 CST 2018
     */
    public void setTemplateName(String templateName) {
        this.templateName = templateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template_manager.active_id
     *
     * @return the value of t_template_manager.active_id
     *
     * @mbggenerated Mon Dec 03 17:25:14 CST 2018
     */
    public String getActiveId() {
        return activeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template_manager.active_id
     *
     * @param activeId the value for t_template_manager.active_id
     *
     * @mbggenerated Mon Dec 03 17:25:14 CST 2018
     */
    public void setActiveId(String activeId) {
        this.activeId = activeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template_manager.open_takes_day
     *
     * @return the value of t_template_manager.open_takes_day
     *
     * @mbggenerated Mon Dec 03 17:25:14 CST 2018
     */
    public Integer getOpenTakesDay() {
        return openTakesDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template_manager.open_takes_day
     *
     * @param openTakesDay the value for t_template_manager.open_takes_day
     *
     * @mbggenerated Mon Dec 03 17:25:14 CST 2018
     */
    public void setOpenTakesDay(Integer openTakesDay) {
        this.openTakesDay = openTakesDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template_manager.delay_days
     *
     * @return the value of t_template_manager.delay_days
     *
     * @mbggenerated Mon Dec 03 17:25:14 CST 2018
     */
    public Integer getDelayDays() {
        return delayDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template_manager.delay_days
     *
     * @param delayDays the value for t_template_manager.delay_days
     *
     * @mbggenerated Mon Dec 03 17:25:14 CST 2018
     */
    public void setDelayDays(Integer delayDays) {
        this.delayDays = delayDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template_manager.delay_status
     *
     * @return the value of t_template_manager.delay_status
     *
     * @mbggenerated Mon Dec 03 17:25:14 CST 2018
     */
    public Integer getDelayStatus() {
        return delayStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template_manager.delay_status
     *
     * @param delayStatus the value for t_template_manager.delay_status
     *
     * @mbggenerated Mon Dec 03 17:25:14 CST 2018
     */
    public void setDelayStatus(Integer delayStatus) {
        this.delayStatus = delayStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template_manager.record_time
     *
     * @return the value of t_template_manager.record_time
     *
     * @mbggenerated Mon Dec 03 17:25:14 CST 2018
     */
    public String getRecordTime() {
        return recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template_manager.record_time
     *
     * @param recordTime the value for t_template_manager.record_time
     *
     * @mbggenerated Mon Dec 03 17:25:14 CST 2018
     */
    public void setRecordTime(String recordTime) {
        this.recordTime = recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template_manager.sort
     *
     * @return the value of t_template_manager.sort
     *
     * @mbggenerated Mon Dec 03 17:25:14 CST 2018
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template_manager.sort
     *
     * @param sort the value for t_template_manager.sort
     *
     * @mbggenerated Mon Dec 03 17:25:14 CST 2018
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template_manager.create_people
     *
     * @return the value of t_template_manager.create_people
     *
     * @mbggenerated Mon Dec 03 17:25:14 CST 2018
     */
    public String getCreatePeople() {
        return createPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template_manager.create_people
     *
     * @param createPeople the value for t_template_manager.create_people
     *
     * @mbggenerated Mon Dec 03 17:25:14 CST 2018
     */
    public void setCreatePeople(String createPeople) {
        this.createPeople = createPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template_manager.remark
     *
     * @return the value of t_template_manager.remark
     *
     * @mbggenerated Mon Dec 03 17:25:14 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template_manager.remark
     *
     * @param remark the value for t_template_manager.remark
     *
     * @mbggenerated Mon Dec 03 17:25:14 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Override
    public String toString() {
        return "TemplateManager{" + "id=" + id + ", templateId=" + templateId + ", templateName='" + templateName + '\'' + ", activeId='" + activeId + '\'' + ", openTakesDay=" + openTakesDay + ", delayDays=" + delayDays + ", delayStatus=" + delayStatus + ", recordTime='" + recordTime + '\'' + ", sort=" + sort + ", createPeople='" + createPeople + '\'' + ", remark='" + remark + '\'' + '}';
    }
}