package com.chenyou.pojo;

import java.util.ArrayList;
import java.util.List;

public class VipCountExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_vip_count
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_vip_count
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_vip_count
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vip_count
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    public VipCountExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vip_count
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vip_count
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vip_count
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vip_count
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vip_count
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vip_count
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vip_count
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vip_count
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vip_count
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vip_count
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_vip_count
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andVipIdIsNull() {
            addCriterion("vip_id is null");
            return (Criteria) this;
        }

        public Criteria andVipIdIsNotNull() {
            addCriterion("vip_id is not null");
            return (Criteria) this;
        }

        public Criteria andVipIdEqualTo(Integer value) {
            addCriterion("vip_id =", value, "vipId");
            return (Criteria) this;
        }

        public Criteria andVipIdNotEqualTo(Integer value) {
            addCriterion("vip_id <>", value, "vipId");
            return (Criteria) this;
        }

        public Criteria andVipIdGreaterThan(Integer value) {
            addCriterion("vip_id >", value, "vipId");
            return (Criteria) this;
        }

        public Criteria andVipIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("vip_id >=", value, "vipId");
            return (Criteria) this;
        }

        public Criteria andVipIdLessThan(Integer value) {
            addCriterion("vip_id <", value, "vipId");
            return (Criteria) this;
        }

        public Criteria andVipIdLessThanOrEqualTo(Integer value) {
            addCriterion("vip_id <=", value, "vipId");
            return (Criteria) this;
        }

        public Criteria andVipIdIn(List<Integer> values) {
            addCriterion("vip_id in", values, "vipId");
            return (Criteria) this;
        }

        public Criteria andVipIdNotIn(List<Integer> values) {
            addCriterion("vip_id not in", values, "vipId");
            return (Criteria) this;
        }

        public Criteria andVipIdBetween(Integer value1, Integer value2) {
            addCriterion("vip_id between", value1, value2, "vipId");
            return (Criteria) this;
        }

        public Criteria andVipIdNotBetween(Integer value1, Integer value2) {
            addCriterion("vip_id not between", value1, value2, "vipId");
            return (Criteria) this;
        }

        public Criteria andVipGradeIsNull() {
            addCriterion("vip_grade is null");
            return (Criteria) this;
        }

        public Criteria andVipGradeIsNotNull() {
            addCriterion("vip_grade is not null");
            return (Criteria) this;
        }

        public Criteria andVipGradeEqualTo(String value) {
            addCriterion("vip_grade =", value, "vipGrade");
            return (Criteria) this;
        }

        public Criteria andVipGradeNotEqualTo(String value) {
            addCriterion("vip_grade <>", value, "vipGrade");
            return (Criteria) this;
        }

        public Criteria andVipGradeGreaterThan(String value) {
            addCriterion("vip_grade >", value, "vipGrade");
            return (Criteria) this;
        }

        public Criteria andVipGradeGreaterThanOrEqualTo(String value) {
            addCriterion("vip_grade >=", value, "vipGrade");
            return (Criteria) this;
        }

        public Criteria andVipGradeLessThan(String value) {
            addCriterion("vip_grade <", value, "vipGrade");
            return (Criteria) this;
        }

        public Criteria andVipGradeLessThanOrEqualTo(String value) {
            addCriterion("vip_grade <=", value, "vipGrade");
            return (Criteria) this;
        }

        public Criteria andVipGradeLike(String value) {
            addCriterion("vip_grade like", value, "vipGrade");
            return (Criteria) this;
        }

        public Criteria andVipGradeNotLike(String value) {
            addCriterion("vip_grade not like", value, "vipGrade");
            return (Criteria) this;
        }

        public Criteria andVipGradeIn(List<String> values) {
            addCriterion("vip_grade in", values, "vipGrade");
            return (Criteria) this;
        }

        public Criteria andVipGradeNotIn(List<String> values) {
            addCriterion("vip_grade not in", values, "vipGrade");
            return (Criteria) this;
        }

        public Criteria andVipGradeBetween(String value1, String value2) {
            addCriterion("vip_grade between", value1, value2, "vipGrade");
            return (Criteria) this;
        }

        public Criteria andVipGradeNotBetween(String value1, String value2) {
            addCriterion("vip_grade not between", value1, value2, "vipGrade");
            return (Criteria) this;
        }

        public Criteria andVipOnlineCountIsNull() {
            addCriterion("vip_online_count is null");
            return (Criteria) this;
        }

        public Criteria andVipOnlineCountIsNotNull() {
            addCriterion("vip_online_count is not null");
            return (Criteria) this;
        }

        public Criteria andVipOnlineCountEqualTo(Integer value) {
            addCriterion("vip_online_count =", value, "vipOnlineCount");
            return (Criteria) this;
        }

        public Criteria andVipOnlineCountNotEqualTo(Integer value) {
            addCriterion("vip_online_count <>", value, "vipOnlineCount");
            return (Criteria) this;
        }

        public Criteria andVipOnlineCountGreaterThan(Integer value) {
            addCriterion("vip_online_count >", value, "vipOnlineCount");
            return (Criteria) this;
        }

        public Criteria andVipOnlineCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("vip_online_count >=", value, "vipOnlineCount");
            return (Criteria) this;
        }

        public Criteria andVipOnlineCountLessThan(Integer value) {
            addCriterion("vip_online_count <", value, "vipOnlineCount");
            return (Criteria) this;
        }

        public Criteria andVipOnlineCountLessThanOrEqualTo(Integer value) {
            addCriterion("vip_online_count <=", value, "vipOnlineCount");
            return (Criteria) this;
        }

        public Criteria andVipOnlineCountIn(List<Integer> values) {
            addCriterion("vip_online_count in", values, "vipOnlineCount");
            return (Criteria) this;
        }

        public Criteria andVipOnlineCountNotIn(List<Integer> values) {
            addCriterion("vip_online_count not in", values, "vipOnlineCount");
            return (Criteria) this;
        }

        public Criteria andVipOnlineCountBetween(Integer value1, Integer value2) {
            addCriterion("vip_online_count between", value1, value2, "vipOnlineCount");
            return (Criteria) this;
        }

        public Criteria andVipOnlineCountNotBetween(Integer value1, Integer value2) {
            addCriterion("vip_online_count not between", value1, value2, "vipOnlineCount");
            return (Criteria) this;
        }

        public Criteria andServerIdIsNull() {
            addCriterion("server_id is null");
            return (Criteria) this;
        }

        public Criteria andServerIdIsNotNull() {
            addCriterion("server_id is not null");
            return (Criteria) this;
        }

        public Criteria andServerIdEqualTo(Integer value) {
            addCriterion("server_id =", value, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdNotEqualTo(Integer value) {
            addCriterion("server_id <>", value, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdGreaterThan(Integer value) {
            addCriterion("server_id >", value, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("server_id >=", value, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdLessThan(Integer value) {
            addCriterion("server_id <", value, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdLessThanOrEqualTo(Integer value) {
            addCriterion("server_id <=", value, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdIn(List<Integer> values) {
            addCriterion("server_id in", values, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdNotIn(List<Integer> values) {
            addCriterion("server_id not in", values, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdBetween(Integer value1, Integer value2) {
            addCriterion("server_id between", value1, value2, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("server_id not between", value1, value2, "serverId");
            return (Criteria) this;
        }

        public Criteria andChannelIdIsNull() {
            addCriterion("channel_id is null");
            return (Criteria) this;
        }

        public Criteria andChannelIdIsNotNull() {
            addCriterion("channel_id is not null");
            return (Criteria) this;
        }

        public Criteria andChannelIdEqualTo(Integer value) {
            addCriterion("channel_id =", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdNotEqualTo(Integer value) {
            addCriterion("channel_id <>", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdGreaterThan(Integer value) {
            addCriterion("channel_id >", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("channel_id >=", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdLessThan(Integer value) {
            addCriterion("channel_id <", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdLessThanOrEqualTo(Integer value) {
            addCriterion("channel_id <=", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdIn(List<Integer> values) {
            addCriterion("channel_id in", values, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdNotIn(List<Integer> values) {
            addCriterion("channel_id not in", values, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdBetween(Integer value1, Integer value2) {
            addCriterion("channel_id between", value1, value2, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdNotBetween(Integer value1, Integer value2) {
            addCriterion("channel_id not between", value1, value2, "channelId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_vip_count
     *
     * @mbggenerated do_not_delete_during_merge Fri Sep 14 15:16:37 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_vip_count
     *
     * @mbggenerated Fri Sep 14 15:16:37 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}